#!/bin/bash
#
# Builds users service
#

set -e

HOSTS=( gallery-$ENV gallery-$ENV-4 gallery-$ENV-3 )
declare -A pause=(["prod"]="30s" ["stage"]="20s")

# env BUILD_DIR, ENV

# init
touch "$BUILD_DIR/logs/users.log"

echo "*** logging in $BUILD_DIR/logs/users.log"

exec 7<&1
exec &> "$BUILD_DIR/logs/users.log"

# build 
echo "*** building users"

cd $BUILD_DIR/gallery/server/users
echo "*** pwd = $(pwd)"
go version
[ $? -ne 0 ] && echo "*** go is not installed, exit." && exit 1
go env -w "CGO_ENABLED=1"

go build -v -buildvcs=false ./cmd/grpc/
[ $? -ne 0 ] && echo "*** build failed, exit." && exit 1

go build -v -buildvcs=false ./cmd/http/
[ $? -ne 0 ] && echo "*** build failed, exit." && exit 1

# stop
set +e

for host in ${HOSTS[@]}; do
    echo "*** mv users on $host"
    ssh "$host" "/srv/misc/scripts/stop_users.sh"

    scp grpc "$host:/srv/gallery/$ENV/users/"
    scp http "$host:/srv/gallery/$ENV/users/"

    echo "*** start users on $host"
    ssh "$host" "/srv/misc/scripts/start_users.sh"

    sleep ${pause[$ENV]} # let cluster restart
done

set -e

echo

# restore
echo "*** build finish $(date)"
echo "==="

exec 1<&7 7<&-

echo "done."

exit 0;


