#!/bin/bash
#
# Builds billing service
#

set -e

HOSTS=( gallery-$ENV gallery-$ENV-4 gallery-$ENV-3 )
declare -A pause=(["prod"]="30s" ["stage"]="0")

# env BUILD_DIR, ENV

touch "$BUILD_DIR/logs/billing.log"

echo "*** logging in $BUILD_DIR/logs/billing.log"

exec 7<&1
exec &> "$BUILD_DIR/logs/billing.log"

# build 
echo "*** building billing"

cd $BUILD_DIR/gallery/server/billing
echo "*** pwd = $(pwd)"
go version
[ $? -ne 0 ] && echo "*** go is not installed, exit." && exit 1
go env -w "CGO_ENABLED=1"
go build -v -buildvcs=false ./cmd/grpc/
[ $? -ne 0 ] && echo "*** build failed, exit." && exit 1

go build -v -buildvcs=false ./cmd/http/
[ $? -ne 0 ] && echo "*** build failed, exit." && exit 1

# stop
set +e

for host in ${HOSTS[@]}; do
    echo "*** stop billing on $host"
    ssh "$host" "/srv/misc/scripts/stop_billing.sh"

    scp grpc "$host:/srv/gallery/$ENV/billing/"
    scp http "$host:/srv/gallery/$ENV/billing/"

    echo "*** start billing on $host"
    ssh "$host" "/srv/misc/scripts/start_billing.sh"
    
    sleep ${pause[$ENV]} # let cluster restart
done

set -e

echo

# restore
echo "*** build finish $(date)"
echo "==="

exec 1<&7 7<&-

echo "done."

exit 0;


