#!/bin/bash
#
# Builds sessions service
#

set -e

# env BUILD_DIR, ENV

# init
mkdir -p "/srv/gallery/$ENV/sessions" # no error
touch "$BUILD_DIR/logs/sessions.log"

echo "*** logging in $BUILD_DIR/logs/sessions.log"

exec 7<&1
exec &> "$BUILD_DIR/logs/sessions.log"

# build 
echo "*** building sessions"

cd $BUILD_DIR/gallery/server/sessions
echo "*** pwd = $(pwd)"
go version
[ $? -ne 0 ] && echo "*** go is not installed, exit." && exit 1
go env -w "CGO_ENABLED=1"
go build -v -buildvcs=false ./cmd/grpc/
[ $? -ne 0 ] && echo "*** build failed, exit." && exit 1

# stop
set +e
echo "*** stopping gallery-sessions"
systemd-run --user --scope -p "Delegate=yes" -- lxc-attach gallery-$ENV -- /srv/misc/scripts/stop_sessions.sh

scp grpc gallery-$ENV:/srv/gallery/$ENV/sessions/

# start
echo "*** starting gallery-sessions"
systemd-run --user --scope -p "Delegate=yes" -- lxc-attach gallery-$ENV -- /srv/misc/scripts/start_sessions.sh

set -e

echo

# restore
echo "*** build finish $(date)"
echo "==="

exec 1<&7 7<&-

echo "done."

exit 0;


