#!/bin/bash
#
# Builds files service
#

set -e

# env BUILD_DIR, ENV

# init
touch "$BUILD_DIR/logs/files.log"

echo "*** logging in $BUILD_DIR/logs/files.log"

exec 7<&1
exec &> "$BUILD_DIR/logs/files.log"

# build 
echo "*** building files"

echo "$USER"

cd $BUILD_DIR/gallery/server/files
echo "*** pwd = $(pwd)"
go version
[ $? -ne 0 ] && echo "*** go is not installed, exit." && exit 1
go env -w "CGO_ENABLED=1"

go build -v -buildvcs=false ./cmd/grpc/
[ $? -ne 0 ] && echo "*** build failed, exit." && exit 1

go build -v  -buildvcs=false ./cmd/http/
[ $? -ne 0 ] && echo "*** build failed, exit." && exit 1

# stop
set +e
echo "*** stopping gallery-files"
ssh "gallery-$ENV-files" "/srv/misc/scripts/stop_files.sh"

scp grpc "gallery-$ENV-files:/srv/gallery/$ENV/files/"
scp http "gallery-$ENV-files:/srv/gallery/$ENV/files/"

# start
echo "*** starting gallery-files"
ssh "gallery-$ENV-files" "/srv/misc/scripts/start_files.sh"

set -e

echo

# restore
echo "*** build finish $(date)"
echo "==="

exec 1<&7 7<&-

echo "done."

exit 0;


