#!/bin/bash
#
# Builds gallery front
#

set -e

HOSTS=( gallery-$ENV gallery-$ENV-4 gallery-$ENV-3 )

# env BUILD_DIR, ENV

# init
mkdir -p "/srv/gallery/front" # no error
touch "$BUILD_DIR/logs/front.log"

echo "*** logging in $BUILD_DIR/logs/front.log"

exec 7<&1
exec &> "$BUILD_DIR/logs/front.log"

# build
echo "*** building front"

cd "$BUILD_DIR/gallery/front/"
echo "*** pwd = $(pwd)"
export NODE_ENV="$ENV"
export NODE_CONFIG_ENV="$ENV"
npm install
node "./scripts/build-gui.js"
node "./scripts/build-server.js"

# stop
set +e

for host in ${HOSTS[@]}; do
    echo "*** stopping gallery-front"
    ssh "$host" "/srv/misc/scripts/stop_front.sh"

    scp -r build/* $host:/srv/gallery/$ENV/front/build/
    scp -r templates/* $host:/srv/gallery/$ENV/front/templates/
    scp -r public/* $host:/srv/gallery/$ENV/front/public/
    scp etag $host:/srv/gallery/$ENV/front/

    # start
    echo "*** starting gallery-front"
    ssh "$host" "/srv/misc/scripts/start_front.sh"
done

set -e
echo

# restore
echo "*** build finish $(date)"
echo "==="

exec 1<&7 7<&-

echo "done."

exit 0;


