// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.19.4
// source: protos/billing.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Command struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReqType       int32                  `protobuf:"varint,1,opt,name=req_type,json=reqType,proto3" json:"req_type,omitempty"`
	Cmd           []byte                 `protobuf:"bytes,2,opt,name=cmd,proto3" json:"cmd,omitempty"`
	Duration      string                 `protobuf:"bytes,3,opt,name=duration,proto3" json:"duration,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Command) Reset() {
	*x = Command{}
	mi := &file_protos_billing_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Command) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Command) ProtoMessage() {}

func (x *Command) ProtoReflect() protoreflect.Message {
	mi := &file_protos_billing_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Command.ProtoReflect.Descriptor instead.
func (*Command) Descriptor() ([]byte, []int) {
	return file_protos_billing_proto_rawDescGZIP(), []int{0}
}

func (x *Command) GetReqType() int32 {
	if x != nil {
		return x.ReqType
	}
	return 0
}

func (x *Command) GetCmd() []byte {
	if x != nil {
		return x.Cmd
	}
	return nil
}

func (x *Command) GetDuration() string {
	if x != nil {
		return x.Duration
	}
	return ""
}

type CommandResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Err           *string                `protobuf:"bytes,1,opt,name=err,proto3,oneof" json:"err,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandResponse) Reset() {
	*x = CommandResponse{}
	mi := &file_protos_billing_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandResponse) ProtoMessage() {}

func (x *CommandResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_billing_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandResponse.ProtoReflect.Descriptor instead.
func (*CommandResponse) Descriptor() ([]byte, []int) {
	return file_protos_billing_proto_rawDescGZIP(), []int{1}
}

func (x *CommandResponse) GetErr() string {
	if x != nil && x.Err != nil {
		return *x.Err
	}
	return ""
}

type BillingSnapshot struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Item:
	//
	//	*BillingSnapshot_Invoice
	//	*BillingSnapshot_Payment
	Item          isBillingSnapshot_Item `protobuf_oneof:"Item"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BillingSnapshot) Reset() {
	*x = BillingSnapshot{}
	mi := &file_protos_billing_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BillingSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BillingSnapshot) ProtoMessage() {}

func (x *BillingSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_protos_billing_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BillingSnapshot.ProtoReflect.Descriptor instead.
func (*BillingSnapshot) Descriptor() ([]byte, []int) {
	return file_protos_billing_proto_rawDescGZIP(), []int{2}
}

func (x *BillingSnapshot) GetItem() isBillingSnapshot_Item {
	if x != nil {
		return x.Item
	}
	return nil
}

func (x *BillingSnapshot) GetInvoice() *InvoiceSnapshotItem {
	if x != nil {
		if x, ok := x.Item.(*BillingSnapshot_Invoice); ok {
			return x.Invoice
		}
	}
	return nil
}

func (x *BillingSnapshot) GetPayment() *PaymentSnapshotItem {
	if x != nil {
		if x, ok := x.Item.(*BillingSnapshot_Payment); ok {
			return x.Payment
		}
	}
	return nil
}

type isBillingSnapshot_Item interface {
	isBillingSnapshot_Item()
}

type BillingSnapshot_Invoice struct {
	Invoice *InvoiceSnapshotItem `protobuf:"bytes,1,opt,name=invoice,proto3,oneof"`
}

type BillingSnapshot_Payment struct {
	Payment *PaymentSnapshotItem `protobuf:"bytes,2,opt,name=payment,proto3,oneof"`
}

func (*BillingSnapshot_Invoice) isBillingSnapshot_Item() {}

func (*BillingSnapshot_Payment) isBillingSnapshot_Item() {}

type InvoiceSnapshotItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	Total         int64                  `protobuf:"varint,4,opt,name=total,proto3" json:"total,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Cart          []byte                 `protobuf:"bytes,7,opt,name=cart,proto3" json:"cart,omitempty"`
	Metadata      []byte                 `protobuf:"bytes,8,opt,name=metadata,proto3,oneof" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InvoiceSnapshotItem) Reset() {
	*x = InvoiceSnapshotItem{}
	mi := &file_protos_billing_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvoiceSnapshotItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvoiceSnapshotItem) ProtoMessage() {}

func (x *InvoiceSnapshotItem) ProtoReflect() protoreflect.Message {
	mi := &file_protos_billing_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvoiceSnapshotItem.ProtoReflect.Descriptor instead.
func (*InvoiceSnapshotItem) Descriptor() ([]byte, []int) {
	return file_protos_billing_proto_rawDescGZIP(), []int{3}
}

func (x *InvoiceSnapshotItem) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *InvoiceSnapshotItem) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *InvoiceSnapshotItem) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *InvoiceSnapshotItem) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *InvoiceSnapshotItem) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *InvoiceSnapshotItem) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *InvoiceSnapshotItem) GetCart() []byte {
	if x != nil {
		return x.Cart
	}
	return nil
}

func (x *InvoiceSnapshotItem) GetMetadata() []byte {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type PaymentSnapshotItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	InvoiceId     string                 `protobuf:"bytes,3,opt,name=invoice_id,json=invoiceId,proto3" json:"invoice_id,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	Currency      string                 `protobuf:"bytes,5,opt,name=currency,proto3" json:"currency,omitempty"`
	Total         int64                  `protobuf:"varint,6,opt,name=total,proto3" json:"total,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Metadata      []byte                 `protobuf:"bytes,9,opt,name=metadata,proto3,oneof" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaymentSnapshotItem) Reset() {
	*x = PaymentSnapshotItem{}
	mi := &file_protos_billing_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaymentSnapshotItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentSnapshotItem) ProtoMessage() {}

func (x *PaymentSnapshotItem) ProtoReflect() protoreflect.Message {
	mi := &file_protos_billing_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentSnapshotItem.ProtoReflect.Descriptor instead.
func (*PaymentSnapshotItem) Descriptor() ([]byte, []int) {
	return file_protos_billing_proto_rawDescGZIP(), []int{4}
}

func (x *PaymentSnapshotItem) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PaymentSnapshotItem) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *PaymentSnapshotItem) GetInvoiceId() string {
	if x != nil {
		return x.InvoiceId
	}
	return ""
}

func (x *PaymentSnapshotItem) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *PaymentSnapshotItem) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *PaymentSnapshotItem) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *PaymentSnapshotItem) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *PaymentSnapshotItem) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *PaymentSnapshotItem) GetMetadata() []byte {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type Invoice struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	Total         int64                  `protobuf:"varint,4,opt,name=total,proto3" json:"total,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Cart          *Cart                  `protobuf:"bytes,7,opt,name=cart,proto3" json:"cart,omitempty"`
	Metadata      []byte                 `protobuf:"bytes,8,opt,name=metadata,proto3,oneof" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Invoice) Reset() {
	*x = Invoice{}
	mi := &file_protos_billing_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Invoice) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Invoice) ProtoMessage() {}

func (x *Invoice) ProtoReflect() protoreflect.Message {
	mi := &file_protos_billing_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Invoice.ProtoReflect.Descriptor instead.
func (*Invoice) Descriptor() ([]byte, []int) {
	return file_protos_billing_proto_rawDescGZIP(), []int{5}
}

func (x *Invoice) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Invoice) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *Invoice) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Invoice) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *Invoice) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Invoice) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *Invoice) GetCart() *Cart {
	if x != nil {
		return x.Cart
	}
	return nil
}

func (x *Invoice) GetMetadata() []byte {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type Payment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	InvoiceId     string                 `protobuf:"bytes,3,opt,name=invoice_id,json=invoiceId,proto3" json:"invoice_id,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	Currency      string                 `protobuf:"bytes,5,opt,name=currency,proto3" json:"currency,omitempty"`
	Total         int64                  `protobuf:"varint,6,opt,name=total,proto3" json:"total,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Metadata      []byte                 `protobuf:"bytes,9,opt,name=metadata,proto3,oneof" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Payment) Reset() {
	*x = Payment{}
	mi := &file_protos_billing_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Payment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Payment) ProtoMessage() {}

func (x *Payment) ProtoReflect() protoreflect.Message {
	mi := &file_protos_billing_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Payment.ProtoReflect.Descriptor instead.
func (*Payment) Descriptor() ([]byte, []int) {
	return file_protos_billing_proto_rawDescGZIP(), []int{6}
}

func (x *Payment) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Payment) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *Payment) GetInvoiceId() string {
	if x != nil {
		return x.InvoiceId
	}
	return ""
}

func (x *Payment) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Payment) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *Payment) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *Payment) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Payment) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *Payment) GetMetadata() []byte {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type Cart struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*CartItem            `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Cart) Reset() {
	*x = Cart{}
	mi := &file_protos_billing_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Cart) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cart) ProtoMessage() {}

func (x *Cart) ProtoReflect() protoreflect.Message {
	mi := &file_protos_billing_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cart.ProtoReflect.Descriptor instead.
func (*Cart) Descriptor() ([]byte, []int) {
	return file_protos_billing_proto_rawDescGZIP(), []int{7}
}

func (x *Cart) GetItems() []*CartItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type CartItem struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Item:
	//
	//	*CartItem_Premium
	Item          isCartItem_Item `protobuf_oneof:"Item"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CartItem) Reset() {
	*x = CartItem{}
	mi := &file_protos_billing_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CartItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CartItem) ProtoMessage() {}

func (x *CartItem) ProtoReflect() protoreflect.Message {
	mi := &file_protos_billing_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CartItem.ProtoReflect.Descriptor instead.
func (*CartItem) Descriptor() ([]byte, []int) {
	return file_protos_billing_proto_rawDescGZIP(), []int{8}
}

func (x *CartItem) GetItem() isCartItem_Item {
	if x != nil {
		return x.Item
	}
	return nil
}

func (x *CartItem) GetPremium() *Premium {
	if x != nil {
		if x, ok := x.Item.(*CartItem_Premium); ok {
			return x.Premium
		}
	}
	return nil
}

type isCartItem_Item interface {
	isCartItem_Item()
}

type CartItem_Premium struct {
	Premium *Premium `protobuf:"bytes,1,opt,name=premium,proto3,oneof"`
}

func (*CartItem_Premium) isCartItem_Item() {}

type Premium struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExpiresAt     string                 `protobuf:"bytes,1,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	Cost          int64                  `protobuf:"varint,2,opt,name=cost,proto3" json:"cost,omitempty"`
	Discount      int64                  `protobuf:"varint,3,opt,name=discount,proto3" json:"discount,omitempty"`
	Currency      string                 `protobuf:"bytes,4,opt,name=currency,proto3" json:"currency,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Premium) Reset() {
	*x = Premium{}
	mi := &file_protos_billing_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Premium) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Premium) ProtoMessage() {}

func (x *Premium) ProtoReflect() protoreflect.Message {
	mi := &file_protos_billing_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Premium.ProtoReflect.Descriptor instead.
func (*Premium) Descriptor() ([]byte, []int) {
	return file_protos_billing_proto_rawDescGZIP(), []int{9}
}

func (x *Premium) GetExpiresAt() string {
	if x != nil {
		return x.ExpiresAt
	}
	return ""
}

func (x *Premium) GetCost() int64 {
	if x != nil {
		return x.Cost
	}
	return 0
}

func (x *Premium) GetDiscount() int64 {
	if x != nil {
		return x.Discount
	}
	return 0
}

func (x *Premium) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

type GetInvoiceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInvoiceRequest) Reset() {
	*x = GetInvoiceRequest{}
	mi := &file_protos_billing_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInvoiceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInvoiceRequest) ProtoMessage() {}

func (x *GetInvoiceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_billing_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInvoiceRequest.ProtoReflect.Descriptor instead.
func (*GetInvoiceRequest) Descriptor() ([]byte, []int) {
	return file_protos_billing_proto_rawDescGZIP(), []int{10}
}

func (x *GetInvoiceRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetInvoiceRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type GetInvoiceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Invoice       *Invoice               `protobuf:"bytes,1,opt,name=invoice,proto3" json:"invoice,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInvoiceResponse) Reset() {
	*x = GetInvoiceResponse{}
	mi := &file_protos_billing_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInvoiceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInvoiceResponse) ProtoMessage() {}

func (x *GetInvoiceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_billing_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInvoiceResponse.ProtoReflect.Descriptor instead.
func (*GetInvoiceResponse) Descriptor() ([]byte, []int) {
	return file_protos_billing_proto_rawDescGZIP(), []int{11}
}

func (x *GetInvoiceResponse) GetInvoice() *Invoice {
	if x != nil {
		return x.Invoice
	}
	return nil
}

type GetPaymentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPaymentRequest) Reset() {
	*x = GetPaymentRequest{}
	mi := &file_protos_billing_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPaymentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPaymentRequest) ProtoMessage() {}

func (x *GetPaymentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_billing_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPaymentRequest.ProtoReflect.Descriptor instead.
func (*GetPaymentRequest) Descriptor() ([]byte, []int) {
	return file_protos_billing_proto_rawDescGZIP(), []int{12}
}

func (x *GetPaymentRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetPaymentRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type GetPaymentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Payment       *Payment               `protobuf:"bytes,1,opt,name=payment,proto3" json:"payment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPaymentResponse) Reset() {
	*x = GetPaymentResponse{}
	mi := &file_protos_billing_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPaymentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPaymentResponse) ProtoMessage() {}

func (x *GetPaymentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_billing_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPaymentResponse.ProtoReflect.Descriptor instead.
func (*GetPaymentResponse) Descriptor() ([]byte, []int) {
	return file_protos_billing_proto_rawDescGZIP(), []int{13}
}

func (x *GetPaymentResponse) GetPayment() *Payment {
	if x != nil {
		return x.Payment
	}
	return nil
}

var File_protos_billing_proto protoreflect.FileDescriptor

const file_protos_billing_proto_rawDesc = "" +
	"\n" +
	"\x14protos/billing.proto\x12\n" +
	"billing.v1\"R\n" +
	"\aCommand\x12\x19\n" +
	"\breq_type\x18\x01 \x01(\x05R\areqType\x12\x10\n" +
	"\x03cmd\x18\x02 \x01(\fR\x03cmd\x12\x1a\n" +
	"\bduration\x18\x03 \x01(\tR\bduration\"0\n" +
	"\x0fCommandResponse\x12\x15\n" +
	"\x03err\x18\x01 \x01(\tH\x00R\x03err\x88\x01\x01B\x06\n" +
	"\x04_err\"\x93\x01\n" +
	"\x0fBillingSnapshot\x12;\n" +
	"\ainvoice\x18\x01 \x01(\v2\x1f.billing.v1.InvoiceSnapshotItemH\x00R\ainvoice\x12;\n" +
	"\apayment\x18\x02 \x01(\v2\x1f.billing.v1.PaymentSnapshotItemH\x00R\apaymentB\x06\n" +
	"\x04Item\"\xec\x01\n" +
	"\x13InvoiceSnapshotItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x14\n" +
	"\x05total\x18\x04 \x01(\x03R\x05total\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\tR\tupdatedAt\x12\x12\n" +
	"\x04cart\x18\a \x01(\fR\x04cart\x12\x1f\n" +
	"\bmetadata\x18\b \x01(\fH\x00R\bmetadata\x88\x01\x01B\v\n" +
	"\t_metadata\"\x93\x02\n" +
	"\x13PaymentSnapshotItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12\x1d\n" +
	"\n" +
	"invoice_id\x18\x03 \x01(\tR\tinvoiceId\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12\x1a\n" +
	"\bcurrency\x18\x05 \x01(\tR\bcurrency\x12\x14\n" +
	"\x05total\x18\x06 \x01(\x03R\x05total\x12\x1d\n" +
	"\n" +
	"created_at\x18\a \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\b \x01(\tR\tupdatedAt\x12\x1f\n" +
	"\bmetadata\x18\t \x01(\fH\x00R\bmetadata\x88\x01\x01B\v\n" +
	"\t_metadata\"\xf2\x01\n" +
	"\aInvoice\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x14\n" +
	"\x05total\x18\x04 \x01(\x03R\x05total\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\tR\tupdatedAt\x12$\n" +
	"\x04cart\x18\a \x01(\v2\x10.billing.v1.CartR\x04cart\x12\x1f\n" +
	"\bmetadata\x18\b \x01(\fH\x00R\bmetadata\x88\x01\x01B\v\n" +
	"\t_metadata\"\x87\x02\n" +
	"\aPayment\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12\x1d\n" +
	"\n" +
	"invoice_id\x18\x03 \x01(\tR\tinvoiceId\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12\x1a\n" +
	"\bcurrency\x18\x05 \x01(\tR\bcurrency\x12\x14\n" +
	"\x05total\x18\x06 \x01(\x03R\x05total\x12\x1d\n" +
	"\n" +
	"created_at\x18\a \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\b \x01(\tR\tupdatedAt\x12\x1f\n" +
	"\bmetadata\x18\t \x01(\fH\x00R\bmetadata\x88\x01\x01B\v\n" +
	"\t_metadata\"2\n" +
	"\x04Cart\x12*\n" +
	"\x05items\x18\x01 \x03(\v2\x14.billing.v1.CartItemR\x05items\"C\n" +
	"\bCartItem\x12/\n" +
	"\apremium\x18\x01 \x01(\v2\x13.billing.v1.PremiumH\x00R\apremiumB\x06\n" +
	"\x04Item\"t\n" +
	"\aPremium\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x01 \x01(\tR\texpiresAt\x12\x12\n" +
	"\x04cost\x18\x02 \x01(\x03R\x04cost\x12\x1a\n" +
	"\bdiscount\x18\x03 \x01(\x03R\bdiscount\x12\x1a\n" +
	"\bcurrency\x18\x04 \x01(\tR\bcurrency\"<\n" +
	"\x11GetInvoiceRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\"C\n" +
	"\x12GetInvoiceResponse\x12-\n" +
	"\ainvoice\x18\x01 \x01(\v2\x13.billing.v1.InvoiceR\ainvoice\"<\n" +
	"\x11GetPaymentRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\"C\n" +
	"\x12GetPaymentResponse\x12-\n" +
	"\apayment\x18\x01 \x01(\v2\x13.billing.v1.PaymentR\apayment2\xe4\x01\n" +
	"\aBilling\x12;\n" +
	"\x05Apply\x12\x13.billing.v1.Command\x1a\x1b.billing.v1.CommandResponse\"\x00\x12M\n" +
	"\n" +
	"GetInvoice\x12\x1d.billing.v1.GetInvoiceRequest\x1a\x1e.billing.v1.GetInvoiceResponse\"\x00\x12M\n" +
	"\n" +
	"GetPayment\x12\x1d.billing.v1.GetPaymentRequest\x1a\x1e.billing.v1.GetPaymentResponse\"\x00B%Z#github.com/bd878/gallery/server/apib\x06proto3"

var (
	file_protos_billing_proto_rawDescOnce sync.Once
	file_protos_billing_proto_rawDescData []byte
)

func file_protos_billing_proto_rawDescGZIP() []byte {
	file_protos_billing_proto_rawDescOnce.Do(func() {
		file_protos_billing_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protos_billing_proto_rawDesc), len(file_protos_billing_proto_rawDesc)))
	})
	return file_protos_billing_proto_rawDescData
}

var file_protos_billing_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_protos_billing_proto_goTypes = []any{
	(*Command)(nil),             // 0: billing.v1.Command
	(*CommandResponse)(nil),     // 1: billing.v1.CommandResponse
	(*BillingSnapshot)(nil),     // 2: billing.v1.BillingSnapshot
	(*InvoiceSnapshotItem)(nil), // 3: billing.v1.InvoiceSnapshotItem
	(*PaymentSnapshotItem)(nil), // 4: billing.v1.PaymentSnapshotItem
	(*Invoice)(nil),             // 5: billing.v1.Invoice
	(*Payment)(nil),             // 6: billing.v1.Payment
	(*Cart)(nil),                // 7: billing.v1.Cart
	(*CartItem)(nil),            // 8: billing.v1.CartItem
	(*Premium)(nil),             // 9: billing.v1.Premium
	(*GetInvoiceRequest)(nil),   // 10: billing.v1.GetInvoiceRequest
	(*GetInvoiceResponse)(nil),  // 11: billing.v1.GetInvoiceResponse
	(*GetPaymentRequest)(nil),   // 12: billing.v1.GetPaymentRequest
	(*GetPaymentResponse)(nil),  // 13: billing.v1.GetPaymentResponse
}
var file_protos_billing_proto_depIdxs = []int32{
	3,  // 0: billing.v1.BillingSnapshot.invoice:type_name -> billing.v1.InvoiceSnapshotItem
	4,  // 1: billing.v1.BillingSnapshot.payment:type_name -> billing.v1.PaymentSnapshotItem
	7,  // 2: billing.v1.Invoice.cart:type_name -> billing.v1.Cart
	8,  // 3: billing.v1.Cart.items:type_name -> billing.v1.CartItem
	9,  // 4: billing.v1.CartItem.premium:type_name -> billing.v1.Premium
	5,  // 5: billing.v1.GetInvoiceResponse.invoice:type_name -> billing.v1.Invoice
	6,  // 6: billing.v1.GetPaymentResponse.payment:type_name -> billing.v1.Payment
	0,  // 7: billing.v1.Billing.Apply:input_type -> billing.v1.Command
	10, // 8: billing.v1.Billing.GetInvoice:input_type -> billing.v1.GetInvoiceRequest
	12, // 9: billing.v1.Billing.GetPayment:input_type -> billing.v1.GetPaymentRequest
	1,  // 10: billing.v1.Billing.Apply:output_type -> billing.v1.CommandResponse
	11, // 11: billing.v1.Billing.GetInvoice:output_type -> billing.v1.GetInvoiceResponse
	13, // 12: billing.v1.Billing.GetPayment:output_type -> billing.v1.GetPaymentResponse
	10, // [10:13] is the sub-list for method output_type
	7,  // [7:10] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_protos_billing_proto_init() }
func file_protos_billing_proto_init() {
	if File_protos_billing_proto != nil {
		return
	}
	file_protos_billing_proto_msgTypes[1].OneofWrappers = []any{}
	file_protos_billing_proto_msgTypes[2].OneofWrappers = []any{
		(*BillingSnapshot_Invoice)(nil),
		(*BillingSnapshot_Payment)(nil),
	}
	file_protos_billing_proto_msgTypes[3].OneofWrappers = []any{}
	file_protos_billing_proto_msgTypes[4].OneofWrappers = []any{}
	file_protos_billing_proto_msgTypes[5].OneofWrappers = []any{}
	file_protos_billing_proto_msgTypes[6].OneofWrappers = []any{}
	file_protos_billing_proto_msgTypes[8].OneofWrappers = []any{
		(*CartItem_Premium)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protos_billing_proto_rawDesc), len(file_protos_billing_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protos_billing_proto_goTypes,
		DependencyIndexes: file_protos_billing_proto_depIdxs,
		MessageInfos:      file_protos_billing_proto_msgTypes,
	}.Build()
	File_protos_billing_proto = out.File
	file_protos_billing_proto_goTypes = nil
	file_protos_billing_proto_depIdxs = nil
}
