// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.19.4
// source: protos/comments.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CommentSnapshotItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	MessageId     int64                  `protobuf:"varint,2,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	UserId        int64                  `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Text          string                 `protobuf:"bytes,4,opt,name=text,proto3" json:"text,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Metadata      []byte                 `protobuf:"bytes,7,opt,name=metadata,proto3,oneof" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommentSnapshotItem) Reset() {
	*x = CommentSnapshotItem{}
	mi := &file_protos_comments_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommentSnapshotItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommentSnapshotItem) ProtoMessage() {}

func (x *CommentSnapshotItem) ProtoReflect() protoreflect.Message {
	mi := &file_protos_comments_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommentSnapshotItem.ProtoReflect.Descriptor instead.
func (*CommentSnapshotItem) Descriptor() ([]byte, []int) {
	return file_protos_comments_proto_rawDescGZIP(), []int{0}
}

func (x *CommentSnapshotItem) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CommentSnapshotItem) GetMessageId() int64 {
	if x != nil {
		return x.MessageId
	}
	return 0
}

func (x *CommentSnapshotItem) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CommentSnapshotItem) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *CommentSnapshotItem) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *CommentSnapshotItem) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *CommentSnapshotItem) GetMetadata() []byte {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type Comment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	MessageId     int64                  `protobuf:"varint,2,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	UserId        int64                  `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Text          string                 `protobuf:"bytes,4,opt,name=text,proto3" json:"text,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Metadata      []byte                 `protobuf:"bytes,7,opt,name=metadata,proto3,oneof" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Comment) Reset() {
	*x = Comment{}
	mi := &file_protos_comments_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Comment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Comment) ProtoMessage() {}

func (x *Comment) ProtoReflect() protoreflect.Message {
	mi := &file_protos_comments_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Comment.ProtoReflect.Descriptor instead.
func (*Comment) Descriptor() ([]byte, []int) {
	return file_protos_comments_proto_rawDescGZIP(), []int{1}
}

func (x *Comment) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Comment) GetMessageId() int64 {
	if x != nil {
		return x.MessageId
	}
	return 0
}

func (x *Comment) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *Comment) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *Comment) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Comment) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *Comment) GetMetadata() []byte {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type CommentsList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Comments      []*Comment             `protobuf:"bytes,1,rep,name=comments,proto3" json:"comments,omitempty"`
	IsLastPage    bool                   `protobuf:"varint,2,opt,name=is_last_page,json=isLastPage,proto3" json:"is_last_page,omitempty"`
	IsFirstPage   bool                   `protobuf:"varint,3,opt,name=is_first_page,json=isFirstPage,proto3" json:"is_first_page,omitempty"`
	Total         int32                  `protobuf:"varint,4,opt,name=total,proto3" json:"total,omitempty"`
	Count         int32                  `protobuf:"varint,5,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommentsList) Reset() {
	*x = CommentsList{}
	mi := &file_protos_comments_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommentsList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommentsList) ProtoMessage() {}

func (x *CommentsList) ProtoReflect() protoreflect.Message {
	mi := &file_protos_comments_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommentsList.ProtoReflect.Descriptor instead.
func (*CommentsList) Descriptor() ([]byte, []int) {
	return file_protos_comments_proto_rawDescGZIP(), []int{2}
}

func (x *CommentsList) GetComments() []*Comment {
	if x != nil {
		return x.Comments
	}
	return nil
}

func (x *CommentsList) GetIsLastPage() bool {
	if x != nil {
		return x.IsLastPage
	}
	return false
}

func (x *CommentsList) GetIsFirstPage() bool {
	if x != nil {
		return x.IsFirstPage
	}
	return false
}

func (x *CommentsList) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *CommentsList) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type SendCommentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	MessageId     int64                  `protobuf:"varint,2,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	UserId        int64                  `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Text          string                 `protobuf:"bytes,4,opt,name=text,proto3" json:"text,omitempty"`
	Metadata      []byte                 `protobuf:"bytes,5,opt,name=metadata,proto3,oneof" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendCommentRequest) Reset() {
	*x = SendCommentRequest{}
	mi := &file_protos_comments_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendCommentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendCommentRequest) ProtoMessage() {}

func (x *SendCommentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_comments_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendCommentRequest.ProtoReflect.Descriptor instead.
func (*SendCommentRequest) Descriptor() ([]byte, []int) {
	return file_protos_comments_proto_rawDescGZIP(), []int{3}
}

func (x *SendCommentRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SendCommentRequest) GetMessageId() int64 {
	if x != nil {
		return x.MessageId
	}
	return 0
}

func (x *SendCommentRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *SendCommentRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *SendCommentRequest) GetMetadata() []byte {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type SendCommentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendCommentResponse) Reset() {
	*x = SendCommentResponse{}
	mi := &file_protos_comments_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendCommentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendCommentResponse) ProtoMessage() {}

func (x *SendCommentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_comments_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendCommentResponse.ProtoReflect.Descriptor instead.
func (*SendCommentResponse) Descriptor() ([]byte, []int) {
	return file_protos_comments_proto_rawDescGZIP(), []int{4}
}

type ListCommentsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	Asc           bool                   `protobuf:"varint,3,opt,name=asc,proto3" json:"asc,omitempty"`
	MessageId     *int64                 `protobuf:"varint,4,opt,name=message_id,json=messageId,proto3,oneof" json:"message_id,omitempty"`
	UserId        *int64                 `protobuf:"varint,5,opt,name=user_id,json=userId,proto3,oneof" json:"user_id,omitempty"`
	Name          *string                `protobuf:"bytes,6,opt,name=name,proto3,oneof" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCommentsRequest) Reset() {
	*x = ListCommentsRequest{}
	mi := &file_protos_comments_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCommentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCommentsRequest) ProtoMessage() {}

func (x *ListCommentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_comments_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCommentsRequest.ProtoReflect.Descriptor instead.
func (*ListCommentsRequest) Descriptor() ([]byte, []int) {
	return file_protos_comments_proto_rawDescGZIP(), []int{5}
}

func (x *ListCommentsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListCommentsRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ListCommentsRequest) GetAsc() bool {
	if x != nil {
		return x.Asc
	}
	return false
}

func (x *ListCommentsRequest) GetMessageId() int64 {
	if x != nil && x.MessageId != nil {
		return *x.MessageId
	}
	return 0
}

func (x *ListCommentsRequest) GetUserId() int64 {
	if x != nil && x.UserId != nil {
		return *x.UserId
	}
	return 0
}

func (x *ListCommentsRequest) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

type ListCommentsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Comments      []*Comment             `protobuf:"bytes,1,rep,name=comments,proto3" json:"comments,omitempty"`
	IsLastPage    bool                   `protobuf:"varint,2,opt,name=is_last_page,json=isLastPage,proto3" json:"is_last_page,omitempty"`
	IsFirstPage   bool                   `protobuf:"varint,3,opt,name=is_first_page,json=isFirstPage,proto3" json:"is_first_page,omitempty"`
	Total         int32                  `protobuf:"varint,4,opt,name=total,proto3" json:"total,omitempty"`
	Count         int32                  `protobuf:"varint,5,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCommentsResponse) Reset() {
	*x = ListCommentsResponse{}
	mi := &file_protos_comments_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCommentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCommentsResponse) ProtoMessage() {}

func (x *ListCommentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_comments_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCommentsResponse.ProtoReflect.Descriptor instead.
func (*ListCommentsResponse) Descriptor() ([]byte, []int) {
	return file_protos_comments_proto_rawDescGZIP(), []int{6}
}

func (x *ListCommentsResponse) GetComments() []*Comment {
	if x != nil {
		return x.Comments
	}
	return nil
}

func (x *ListCommentsResponse) GetIsLastPage() bool {
	if x != nil {
		return x.IsLastPage
	}
	return false
}

func (x *ListCommentsResponse) GetIsFirstPage() bool {
	if x != nil {
		return x.IsFirstPage
	}
	return false
}

func (x *ListCommentsResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListCommentsResponse) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type UpdateCommentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Text          *string                `protobuf:"bytes,3,opt,name=text,proto3,oneof" json:"text,omitempty"`
	Metadata      []byte                 `protobuf:"bytes,4,opt,name=metadata,proto3,oneof" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCommentRequest) Reset() {
	*x = UpdateCommentRequest{}
	mi := &file_protos_comments_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCommentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCommentRequest) ProtoMessage() {}

func (x *UpdateCommentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_comments_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCommentRequest.ProtoReflect.Descriptor instead.
func (*UpdateCommentRequest) Descriptor() ([]byte, []int) {
	return file_protos_comments_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateCommentRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateCommentRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UpdateCommentRequest) GetText() string {
	if x != nil && x.Text != nil {
		return *x.Text
	}
	return ""
}

func (x *UpdateCommentRequest) GetMetadata() []byte {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type UpdateCommentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCommentResponse) Reset() {
	*x = UpdateCommentResponse{}
	mi := &file_protos_comments_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCommentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCommentResponse) ProtoMessage() {}

func (x *UpdateCommentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_comments_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCommentResponse.ProtoReflect.Descriptor instead.
func (*UpdateCommentResponse) Descriptor() ([]byte, []int) {
	return file_protos_comments_proto_rawDescGZIP(), []int{8}
}

type DeleteCommentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCommentRequest) Reset() {
	*x = DeleteCommentRequest{}
	mi := &file_protos_comments_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCommentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCommentRequest) ProtoMessage() {}

func (x *DeleteCommentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_comments_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCommentRequest.ProtoReflect.Descriptor instead.
func (*DeleteCommentRequest) Descriptor() ([]byte, []int) {
	return file_protos_comments_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteCommentRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *DeleteCommentRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type DeleteCommentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCommentResponse) Reset() {
	*x = DeleteCommentResponse{}
	mi := &file_protos_comments_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCommentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCommentResponse) ProtoMessage() {}

func (x *DeleteCommentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_comments_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCommentResponse.ProtoReflect.Descriptor instead.
func (*DeleteCommentResponse) Descriptor() ([]byte, []int) {
	return file_protos_comments_proto_rawDescGZIP(), []int{10}
}

type ReadCommentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadCommentRequest) Reset() {
	*x = ReadCommentRequest{}
	mi := &file_protos_comments_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadCommentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadCommentRequest) ProtoMessage() {}

func (x *ReadCommentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_comments_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadCommentRequest.ProtoReflect.Descriptor instead.
func (*ReadCommentRequest) Descriptor() ([]byte, []int) {
	return file_protos_comments_proto_rawDescGZIP(), []int{11}
}

func (x *ReadCommentRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ReadCommentRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type ReadCommentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Comment       *Comment               `protobuf:"bytes,1,opt,name=comment,proto3" json:"comment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadCommentResponse) Reset() {
	*x = ReadCommentResponse{}
	mi := &file_protos_comments_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadCommentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadCommentResponse) ProtoMessage() {}

func (x *ReadCommentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_comments_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadCommentResponse.ProtoReflect.Descriptor instead.
func (*ReadCommentResponse) Descriptor() ([]byte, []int) {
	return file_protos_comments_proto_rawDescGZIP(), []int{12}
}

func (x *ReadCommentResponse) GetComment() *Comment {
	if x != nil {
		return x.Comment
	}
	return nil
}

type DeleteMessageCommentsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageId     int64                  `protobuf:"varint,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteMessageCommentsRequest) Reset() {
	*x = DeleteMessageCommentsRequest{}
	mi := &file_protos_comments_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteMessageCommentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMessageCommentsRequest) ProtoMessage() {}

func (x *DeleteMessageCommentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_comments_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMessageCommentsRequest.ProtoReflect.Descriptor instead.
func (*DeleteMessageCommentsRequest) Descriptor() ([]byte, []int) {
	return file_protos_comments_proto_rawDescGZIP(), []int{13}
}

func (x *DeleteMessageCommentsRequest) GetMessageId() int64 {
	if x != nil {
		return x.MessageId
	}
	return 0
}

type DeleteMessageCommentsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteMessageCommentsResponse) Reset() {
	*x = DeleteMessageCommentsResponse{}
	mi := &file_protos_comments_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteMessageCommentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMessageCommentsResponse) ProtoMessage() {}

func (x *DeleteMessageCommentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_comments_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMessageCommentsResponse.ProtoReflect.Descriptor instead.
func (*DeleteMessageCommentsResponse) Descriptor() ([]byte, []int) {
	return file_protos_comments_proto_rawDescGZIP(), []int{14}
}

var File_protos_comments_proto protoreflect.FileDescriptor

const file_protos_comments_proto_rawDesc = "" +
	"\n" +
	"\x15protos/comments.proto\x12\vcomments.v1\"\xdd\x01\n" +
	"\x13CommentSnapshotItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1d\n" +
	"\n" +
	"message_id\x18\x02 \x01(\x03R\tmessageId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\x03R\x06userId\x12\x12\n" +
	"\x04text\x18\x04 \x01(\tR\x04text\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\tR\tupdatedAt\x12\x1f\n" +
	"\bmetadata\x18\a \x01(\fH\x00R\bmetadata\x88\x01\x01B\v\n" +
	"\t_metadata\"\xd1\x01\n" +
	"\aComment\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1d\n" +
	"\n" +
	"message_id\x18\x02 \x01(\x03R\tmessageId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\x03R\x06userId\x12\x12\n" +
	"\x04text\x18\x04 \x01(\tR\x04text\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\tR\tupdatedAt\x12\x1f\n" +
	"\bmetadata\x18\a \x01(\fH\x00R\bmetadata\x88\x01\x01B\v\n" +
	"\t_metadata\"\xb2\x01\n" +
	"\fCommentsList\x120\n" +
	"\bcomments\x18\x01 \x03(\v2\x14.comments.v1.CommentR\bcomments\x12 \n" +
	"\fis_last_page\x18\x02 \x01(\bR\n" +
	"isLastPage\x12\"\n" +
	"\ris_first_page\x18\x03 \x01(\bR\visFirstPage\x12\x14\n" +
	"\x05total\x18\x04 \x01(\x05R\x05total\x12\x14\n" +
	"\x05count\x18\x05 \x01(\x05R\x05count\"\x9e\x01\n" +
	"\x12SendCommentRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1d\n" +
	"\n" +
	"message_id\x18\x02 \x01(\x03R\tmessageId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\x03R\x06userId\x12\x12\n" +
	"\x04text\x18\x04 \x01(\tR\x04text\x12\x1f\n" +
	"\bmetadata\x18\x05 \x01(\fH\x00R\bmetadata\x88\x01\x01B\v\n" +
	"\t_metadata\"\x15\n" +
	"\x13SendCommentResponse\"\xd4\x01\n" +
	"\x13ListCommentsRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x05R\x06offset\x12\x10\n" +
	"\x03asc\x18\x03 \x01(\bR\x03asc\x12\"\n" +
	"\n" +
	"message_id\x18\x04 \x01(\x03H\x00R\tmessageId\x88\x01\x01\x12\x1c\n" +
	"\auser_id\x18\x05 \x01(\x03H\x01R\x06userId\x88\x01\x01\x12\x17\n" +
	"\x04name\x18\x06 \x01(\tH\x02R\x04name\x88\x01\x01B\r\n" +
	"\v_message_idB\n" +
	"\n" +
	"\b_user_idB\a\n" +
	"\x05_name\"\xba\x01\n" +
	"\x14ListCommentsResponse\x120\n" +
	"\bcomments\x18\x01 \x03(\v2\x14.comments.v1.CommentR\bcomments\x12 \n" +
	"\fis_last_page\x18\x02 \x01(\bR\n" +
	"isLastPage\x12\"\n" +
	"\ris_first_page\x18\x03 \x01(\bR\visFirstPage\x12\x14\n" +
	"\x05total\x18\x04 \x01(\x05R\x05total\x12\x14\n" +
	"\x05count\x18\x05 \x01(\x05R\x05count\"\x8f\x01\n" +
	"\x14UpdateCommentRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12\x17\n" +
	"\x04text\x18\x03 \x01(\tH\x00R\x04text\x88\x01\x01\x12\x1f\n" +
	"\bmetadata\x18\x04 \x01(\fH\x01R\bmetadata\x88\x01\x01B\a\n" +
	"\x05_textB\v\n" +
	"\t_metadata\"\x17\n" +
	"\x15UpdateCommentResponse\"?\n" +
	"\x14DeleteCommentRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\"\x17\n" +
	"\x15DeleteCommentResponse\"=\n" +
	"\x12ReadCommentRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\"E\n" +
	"\x13ReadCommentResponse\x12.\n" +
	"\acomment\x18\x01 \x01(\v2\x14.comments.v1.CommentR\acomment\"=\n" +
	"\x1cDeleteMessageCommentsRequest\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\x03R\tmessageId\"\x1f\n" +
	"\x1dDeleteMessageCommentsResponse2\xa3\x04\n" +
	"\bComments\x12P\n" +
	"\vSendComment\x12\x1f.comments.v1.SendCommentRequest\x1a .comments.v1.SendCommentResponse\x12V\n" +
	"\rUpdateComment\x12!.comments.v1.UpdateCommentRequest\x1a\".comments.v1.UpdateCommentResponse\x12V\n" +
	"\rDeleteComment\x12!.comments.v1.DeleteCommentRequest\x1a\".comments.v1.DeleteCommentResponse\x12n\n" +
	"\x15DeleteMessageComments\x12).comments.v1.DeleteMessageCommentsRequest\x1a*.comments.v1.DeleteMessageCommentsResponse\x12P\n" +
	"\vReadComment\x12\x1f.comments.v1.ReadCommentRequest\x1a .comments.v1.ReadCommentResponse\x12S\n" +
	"\fListComments\x12 .comments.v1.ListCommentsRequest\x1a!.comments.v1.ListCommentsResponseB%Z#github.com/bd878/gallery/server/apib\x06proto3"

var (
	file_protos_comments_proto_rawDescOnce sync.Once
	file_protos_comments_proto_rawDescData []byte
)

func file_protos_comments_proto_rawDescGZIP() []byte {
	file_protos_comments_proto_rawDescOnce.Do(func() {
		file_protos_comments_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protos_comments_proto_rawDesc), len(file_protos_comments_proto_rawDesc)))
	})
	return file_protos_comments_proto_rawDescData
}

var file_protos_comments_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_protos_comments_proto_goTypes = []any{
	(*CommentSnapshotItem)(nil),           // 0: comments.v1.CommentSnapshotItem
	(*Comment)(nil),                       // 1: comments.v1.Comment
	(*CommentsList)(nil),                  // 2: comments.v1.CommentsList
	(*SendCommentRequest)(nil),            // 3: comments.v1.SendCommentRequest
	(*SendCommentResponse)(nil),           // 4: comments.v1.SendCommentResponse
	(*ListCommentsRequest)(nil),           // 5: comments.v1.ListCommentsRequest
	(*ListCommentsResponse)(nil),          // 6: comments.v1.ListCommentsResponse
	(*UpdateCommentRequest)(nil),          // 7: comments.v1.UpdateCommentRequest
	(*UpdateCommentResponse)(nil),         // 8: comments.v1.UpdateCommentResponse
	(*DeleteCommentRequest)(nil),          // 9: comments.v1.DeleteCommentRequest
	(*DeleteCommentResponse)(nil),         // 10: comments.v1.DeleteCommentResponse
	(*ReadCommentRequest)(nil),            // 11: comments.v1.ReadCommentRequest
	(*ReadCommentResponse)(nil),           // 12: comments.v1.ReadCommentResponse
	(*DeleteMessageCommentsRequest)(nil),  // 13: comments.v1.DeleteMessageCommentsRequest
	(*DeleteMessageCommentsResponse)(nil), // 14: comments.v1.DeleteMessageCommentsResponse
}
var file_protos_comments_proto_depIdxs = []int32{
	1,  // 0: comments.v1.CommentsList.comments:type_name -> comments.v1.Comment
	1,  // 1: comments.v1.ListCommentsResponse.comments:type_name -> comments.v1.Comment
	1,  // 2: comments.v1.ReadCommentResponse.comment:type_name -> comments.v1.Comment
	3,  // 3: comments.v1.Comments.SendComment:input_type -> comments.v1.SendCommentRequest
	7,  // 4: comments.v1.Comments.UpdateComment:input_type -> comments.v1.UpdateCommentRequest
	9,  // 5: comments.v1.Comments.DeleteComment:input_type -> comments.v1.DeleteCommentRequest
	13, // 6: comments.v1.Comments.DeleteMessageComments:input_type -> comments.v1.DeleteMessageCommentsRequest
	11, // 7: comments.v1.Comments.ReadComment:input_type -> comments.v1.ReadCommentRequest
	5,  // 8: comments.v1.Comments.ListComments:input_type -> comments.v1.ListCommentsRequest
	4,  // 9: comments.v1.Comments.SendComment:output_type -> comments.v1.SendCommentResponse
	8,  // 10: comments.v1.Comments.UpdateComment:output_type -> comments.v1.UpdateCommentResponse
	10, // 11: comments.v1.Comments.DeleteComment:output_type -> comments.v1.DeleteCommentResponse
	14, // 12: comments.v1.Comments.DeleteMessageComments:output_type -> comments.v1.DeleteMessageCommentsResponse
	12, // 13: comments.v1.Comments.ReadComment:output_type -> comments.v1.ReadCommentResponse
	6,  // 14: comments.v1.Comments.ListComments:output_type -> comments.v1.ListCommentsResponse
	9,  // [9:15] is the sub-list for method output_type
	3,  // [3:9] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_protos_comments_proto_init() }
func file_protos_comments_proto_init() {
	if File_protos_comments_proto != nil {
		return
	}
	file_protos_comments_proto_msgTypes[0].OneofWrappers = []any{}
	file_protos_comments_proto_msgTypes[1].OneofWrappers = []any{}
	file_protos_comments_proto_msgTypes[3].OneofWrappers = []any{}
	file_protos_comments_proto_msgTypes[5].OneofWrappers = []any{}
	file_protos_comments_proto_msgTypes[7].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protos_comments_proto_rawDesc), len(file_protos_comments_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protos_comments_proto_goTypes,
		DependencyIndexes: file_protos_comments_proto_depIdxs,
		MessageInfos:      file_protos_comments_proto_msgTypes,
	}.Build()
	File_protos_comments_proto = out.File
	file_protos_comments_proto_goTypes = nil
	file_protos_comments_proto_depIdxs = nil
}
