// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.19.4
// source: protos/files_events.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FileUploaded struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId      int64  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Name        string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Description string `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Size        int64  `protobuf:"varint,5,opt,name=size,proto3" json:"size,omitempty"`
	Mime        string `protobuf:"bytes,6,opt,name=mime,proto3" json:"mime,omitempty"`
	Private     bool   `protobuf:"varint,7,opt,name=private,proto3" json:"private,omitempty"`
}

func (x *FileUploaded) Reset() {
	*x = FileUploaded{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_files_events_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FileUploaded) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileUploaded) ProtoMessage() {}

func (x *FileUploaded) ProtoReflect() protoreflect.Message {
	mi := &file_protos_files_events_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileUploaded.ProtoReflect.Descriptor instead.
func (*FileUploaded) Descriptor() ([]byte, []int) {
	return file_protos_files_events_proto_rawDescGZIP(), []int{0}
}

func (x *FileUploaded) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *FileUploaded) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *FileUploaded) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FileUploaded) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *FileUploaded) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *FileUploaded) GetMime() string {
	if x != nil {
		return x.Mime
	}
	return ""
}

func (x *FileUploaded) GetPrivate() bool {
	if x != nil {
		return x.Private
	}
	return false
}

type FileDeleted struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId int64  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Name   string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *FileDeleted) Reset() {
	*x = FileDeleted{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_files_events_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FileDeleted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileDeleted) ProtoMessage() {}

func (x *FileDeleted) ProtoReflect() protoreflect.Message {
	mi := &file_protos_files_events_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileDeleted.ProtoReflect.Descriptor instead.
func (*FileDeleted) Descriptor() ([]byte, []int) {
	return file_protos_files_events_proto_rawDescGZIP(), []int{1}
}

func (x *FileDeleted) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *FileDeleted) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *FileDeleted) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type FilePublished struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId int64 `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
}

func (x *FilePublished) Reset() {
	*x = FilePublished{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_files_events_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FilePublished) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FilePublished) ProtoMessage() {}

func (x *FilePublished) ProtoReflect() protoreflect.Message {
	mi := &file_protos_files_events_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FilePublished.ProtoReflect.Descriptor instead.
func (*FilePublished) Descriptor() ([]byte, []int) {
	return file_protos_files_events_proto_rawDescGZIP(), []int{2}
}

func (x *FilePublished) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *FilePublished) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type FilePrivated struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId int64 `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
}

func (x *FilePrivated) Reset() {
	*x = FilePrivated{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_files_events_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FilePrivated) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FilePrivated) ProtoMessage() {}

func (x *FilePrivated) ProtoReflect() protoreflect.Message {
	mi := &file_protos_files_events_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FilePrivated.ProtoReflect.Descriptor instead.
func (*FilePrivated) Descriptor() ([]byte, []int) {
	return file_protos_files_events_proto_rawDescGZIP(), []int{3}
}

func (x *FilePrivated) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *FilePrivated) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

var File_protos_files_events_proto protoreflect.FileDescriptor

var file_protos_files_events_proto_rawDesc = []byte{
	0x0a, 0x19, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x5f, 0x65,
	0x76, 0x65, 0x6e, 0x74, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0f, 0x66, 0x69, 0x6c,
	0x65, 0x73, 0x5f, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x2e, 0x76, 0x31, 0x22, 0xaf, 0x01, 0x0a,
	0x0c, 0x46, 0x69, 0x6c, 0x65, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x65, 0x64, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x17, 0x0a,
	0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06,
	0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65,
	0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04,
	0x73, 0x69, 0x7a, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x73, 0x69, 0x7a, 0x65,
	0x12, 0x12, 0x0a, 0x04, 0x6d, 0x69, 0x6d, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x6d, 0x69, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x18,
	0x07, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x22, 0x4a,
	0x0a, 0x0b, 0x46, 0x69, 0x6c, 0x65, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x17, 0x0a,
	0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06,
	0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x38, 0x0a, 0x0d, 0x46, 0x69,
	0x6c, 0x65, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x65, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x75,
	0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x75, 0x73,
	0x65, 0x72, 0x49, 0x64, 0x22, 0x37, 0x0a, 0x0c, 0x46, 0x69, 0x6c, 0x65, 0x50, 0x72, 0x69, 0x76,
	0x61, 0x74, 0x65, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x02, 0x69, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x42, 0x25, 0x5a,
	0x23, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x62, 0x64, 0x38, 0x37,
	0x38, 0x2f, 0x67, 0x61, 0x6c, 0x6c, 0x65, 0x72, 0x79, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72,
	0x2f, 0x61, 0x70, 0x69, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protos_files_events_proto_rawDescOnce sync.Once
	file_protos_files_events_proto_rawDescData = file_protos_files_events_proto_rawDesc
)

func file_protos_files_events_proto_rawDescGZIP() []byte {
	file_protos_files_events_proto_rawDescOnce.Do(func() {
		file_protos_files_events_proto_rawDescData = protoimpl.X.CompressGZIP(file_protos_files_events_proto_rawDescData)
	})
	return file_protos_files_events_proto_rawDescData
}

var file_protos_files_events_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_protos_files_events_proto_goTypes = []interface{}{
	(*FileUploaded)(nil),  // 0: files_events.v1.FileUploaded
	(*FileDeleted)(nil),   // 1: files_events.v1.FileDeleted
	(*FilePublished)(nil), // 2: files_events.v1.FilePublished
	(*FilePrivated)(nil),  // 3: files_events.v1.FilePrivated
}
var file_protos_files_events_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_protos_files_events_proto_init() }
func file_protos_files_events_proto_init() {
	if File_protos_files_events_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protos_files_events_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FileUploaded); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_files_events_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FileDeleted); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_files_events_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FilePublished); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_files_events_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FilePrivated); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protos_files_events_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protos_files_events_proto_goTypes,
		DependencyIndexes: file_protos_files_events_proto_depIdxs,
		MessageInfos:      file_protos_files_events_proto_msgTypes,
	}.Build()
	File_protos_files_events_proto = out.File
	file_protos_files_events_proto_rawDesc = nil
	file_protos_files_events_proto_goTypes = nil
	file_protos_files_events_proto_depIdxs = nil
}
