// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.19.4
// source: protos/search.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SearchSnapshot struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Item:
	//
	//	*SearchSnapshot_Message
	//	*SearchSnapshot_File
	//	*SearchSnapshot_Thread
	//	*SearchSnapshot_Translation
	Item          isSearchSnapshot_Item `protobuf_oneof:"Item"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchSnapshot) Reset() {
	*x = SearchSnapshot{}
	mi := &file_protos_search_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchSnapshot) ProtoMessage() {}

func (x *SearchSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_protos_search_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchSnapshot.ProtoReflect.Descriptor instead.
func (*SearchSnapshot) Descriptor() ([]byte, []int) {
	return file_protos_search_proto_rawDescGZIP(), []int{0}
}

func (x *SearchSnapshot) GetItem() isSearchSnapshot_Item {
	if x != nil {
		return x.Item
	}
	return nil
}

func (x *SearchSnapshot) GetMessage() *SearchMessageSnapshotItem {
	if x != nil {
		if x, ok := x.Item.(*SearchSnapshot_Message); ok {
			return x.Message
		}
	}
	return nil
}

func (x *SearchSnapshot) GetFile() *SearchFileSnapshotItem {
	if x != nil {
		if x, ok := x.Item.(*SearchSnapshot_File); ok {
			return x.File
		}
	}
	return nil
}

func (x *SearchSnapshot) GetThread() *SearchThreadSnapshotItem {
	if x != nil {
		if x, ok := x.Item.(*SearchSnapshot_Thread); ok {
			return x.Thread
		}
	}
	return nil
}

func (x *SearchSnapshot) GetTranslation() *SearchTranslationSnapshotItem {
	if x != nil {
		if x, ok := x.Item.(*SearchSnapshot_Translation); ok {
			return x.Translation
		}
	}
	return nil
}

type isSearchSnapshot_Item interface {
	isSearchSnapshot_Item()
}

type SearchSnapshot_Message struct {
	Message *SearchMessageSnapshotItem `protobuf:"bytes,1,opt,name=message,proto3,oneof"`
}

type SearchSnapshot_File struct {
	File *SearchFileSnapshotItem `protobuf:"bytes,2,opt,name=file,proto3,oneof"`
}

type SearchSnapshot_Thread struct {
	Thread *SearchThreadSnapshotItem `protobuf:"bytes,3,opt,name=thread,proto3,oneof"`
}

type SearchSnapshot_Translation struct {
	Translation *SearchTranslationSnapshotItem `protobuf:"bytes,4,opt,name=translation,proto3,oneof"`
}

func (*SearchSnapshot_Message) isSearchSnapshot_Item() {}

func (*SearchSnapshot_File) isSearchSnapshot_Item() {}

func (*SearchSnapshot_Thread) isSearchSnapshot_Item() {}

func (*SearchSnapshot_Translation) isSearchSnapshot_Item() {}

type SearchMessageSnapshotItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Name          string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Text          string                 `protobuf:"bytes,5,opt,name=text,proto3" json:"text,omitempty"`
	Private       bool                   `protobuf:"varint,6,opt,name=private,proto3" json:"private,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchMessageSnapshotItem) Reset() {
	*x = SearchMessageSnapshotItem{}
	mi := &file_protos_search_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchMessageSnapshotItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchMessageSnapshotItem) ProtoMessage() {}

func (x *SearchMessageSnapshotItem) ProtoReflect() protoreflect.Message {
	mi := &file_protos_search_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchMessageSnapshotItem.ProtoReflect.Descriptor instead.
func (*SearchMessageSnapshotItem) Descriptor() ([]byte, []int) {
	return file_protos_search_proto_rawDescGZIP(), []int{1}
}

func (x *SearchMessageSnapshotItem) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SearchMessageSnapshotItem) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *SearchMessageSnapshotItem) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *SearchMessageSnapshotItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SearchMessageSnapshotItem) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *SearchMessageSnapshotItem) GetPrivate() bool {
	if x != nil {
		return x.Private
	}
	return false
}

func (x *SearchMessageSnapshotItem) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *SearchMessageSnapshotItem) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type SearchFileSnapshotItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Mime          string                 `protobuf:"bytes,4,opt,name=mime,proto3" json:"mime,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Size          int64                  `protobuf:"varint,7,opt,name=size,proto3" json:"size,omitempty"`
	Private       bool                   `protobuf:"varint,8,opt,name=private,proto3" json:"private,omitempty"`
	Description   string                 `protobuf:"bytes,9,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchFileSnapshotItem) Reset() {
	*x = SearchFileSnapshotItem{}
	mi := &file_protos_search_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchFileSnapshotItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchFileSnapshotItem) ProtoMessage() {}

func (x *SearchFileSnapshotItem) ProtoReflect() protoreflect.Message {
	mi := &file_protos_search_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchFileSnapshotItem.ProtoReflect.Descriptor instead.
func (*SearchFileSnapshotItem) Descriptor() ([]byte, []int) {
	return file_protos_search_proto_rawDescGZIP(), []int{2}
}

func (x *SearchFileSnapshotItem) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SearchFileSnapshotItem) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *SearchFileSnapshotItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SearchFileSnapshotItem) GetMime() string {
	if x != nil {
		return x.Mime
	}
	return ""
}

func (x *SearchFileSnapshotItem) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *SearchFileSnapshotItem) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *SearchFileSnapshotItem) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *SearchFileSnapshotItem) GetPrivate() bool {
	if x != nil {
		return x.Private
	}
	return false
}

func (x *SearchFileSnapshotItem) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type SearchThreadSnapshotItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ParentId      int64                  `protobuf:"varint,3,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	Name          string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	Private       bool                   `protobuf:"varint,6,opt,name=private,proto3" json:"private,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchThreadSnapshotItem) Reset() {
	*x = SearchThreadSnapshotItem{}
	mi := &file_protos_search_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchThreadSnapshotItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchThreadSnapshotItem) ProtoMessage() {}

func (x *SearchThreadSnapshotItem) ProtoReflect() protoreflect.Message {
	mi := &file_protos_search_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchThreadSnapshotItem.ProtoReflect.Descriptor instead.
func (*SearchThreadSnapshotItem) Descriptor() ([]byte, []int) {
	return file_protos_search_proto_rawDescGZIP(), []int{3}
}

func (x *SearchThreadSnapshotItem) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SearchThreadSnapshotItem) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *SearchThreadSnapshotItem) GetParentId() int64 {
	if x != nil {
		return x.ParentId
	}
	return 0
}

func (x *SearchThreadSnapshotItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SearchThreadSnapshotItem) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *SearchThreadSnapshotItem) GetPrivate() bool {
	if x != nil {
		return x.Private
	}
	return false
}

func (x *SearchThreadSnapshotItem) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *SearchThreadSnapshotItem) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type SearchTranslationSnapshotItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageId     int64                  `protobuf:"varint,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Lang          string                 `protobuf:"bytes,3,opt,name=lang,proto3" json:"lang,omitempty"`
	Text          string                 `protobuf:"bytes,4,opt,name=text,proto3" json:"text,omitempty"`
	Title         string                 `protobuf:"bytes,5,opt,name=title,proto3" json:"title,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchTranslationSnapshotItem) Reset() {
	*x = SearchTranslationSnapshotItem{}
	mi := &file_protos_search_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchTranslationSnapshotItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchTranslationSnapshotItem) ProtoMessage() {}

func (x *SearchTranslationSnapshotItem) ProtoReflect() protoreflect.Message {
	mi := &file_protos_search_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchTranslationSnapshotItem.ProtoReflect.Descriptor instead.
func (*SearchTranslationSnapshotItem) Descriptor() ([]byte, []int) {
	return file_protos_search_proto_rawDescGZIP(), []int{4}
}

func (x *SearchTranslationSnapshotItem) GetMessageId() int64 {
	if x != nil {
		return x.MessageId
	}
	return 0
}

func (x *SearchTranslationSnapshotItem) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *SearchTranslationSnapshotItem) GetLang() string {
	if x != nil {
		return x.Lang
	}
	return ""
}

func (x *SearchTranslationSnapshotItem) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *SearchTranslationSnapshotItem) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *SearchTranslationSnapshotItem) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *SearchTranslationSnapshotItem) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type SearchMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Name          string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Text          string                 `protobuf:"bytes,5,opt,name=text,proto3" json:"text,omitempty"`
	Private       bool                   `protobuf:"varint,6,opt,name=private,proto3" json:"private,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchMessage) Reset() {
	*x = SearchMessage{}
	mi := &file_protos_search_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchMessage) ProtoMessage() {}

func (x *SearchMessage) ProtoReflect() protoreflect.Message {
	mi := &file_protos_search_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchMessage.ProtoReflect.Descriptor instead.
func (*SearchMessage) Descriptor() ([]byte, []int) {
	return file_protos_search_proto_rawDescGZIP(), []int{5}
}

func (x *SearchMessage) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SearchMessage) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *SearchMessage) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *SearchMessage) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SearchMessage) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *SearchMessage) GetPrivate() bool {
	if x != nil {
		return x.Private
	}
	return false
}

func (x *SearchMessage) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *SearchMessage) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type SearchFile struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchFile) Reset() {
	*x = SearchFile{}
	mi := &file_protos_search_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchFile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchFile) ProtoMessage() {}

func (x *SearchFile) ProtoReflect() protoreflect.Message {
	mi := &file_protos_search_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchFile.ProtoReflect.Descriptor instead.
func (*SearchFile) Descriptor() ([]byte, []int) {
	return file_protos_search_proto_rawDescGZIP(), []int{6}
}

func (x *SearchFile) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SearchFile) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *SearchFile) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SearchFile) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *SearchFile) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type SearchMessagesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Substr        string                 `protobuf:"bytes,1,opt,name=substr,proto3" json:"substr,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ThreadId      *int64                 `protobuf:"varint,3,opt,name=thread_id,json=threadId,proto3,oneof" json:"thread_id,omitempty"`
	Public        *int32                 `protobuf:"varint,4,opt,name=public,proto3,oneof" json:"public,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchMessagesRequest) Reset() {
	*x = SearchMessagesRequest{}
	mi := &file_protos_search_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchMessagesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchMessagesRequest) ProtoMessage() {}

func (x *SearchMessagesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_search_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchMessagesRequest.ProtoReflect.Descriptor instead.
func (*SearchMessagesRequest) Descriptor() ([]byte, []int) {
	return file_protos_search_proto_rawDescGZIP(), []int{7}
}

func (x *SearchMessagesRequest) GetSubstr() string {
	if x != nil {
		return x.Substr
	}
	return ""
}

func (x *SearchMessagesRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *SearchMessagesRequest) GetThreadId() int64 {
	if x != nil && x.ThreadId != nil {
		return *x.ThreadId
	}
	return 0
}

func (x *SearchMessagesRequest) GetPublic() int32 {
	if x != nil && x.Public != nil {
		return *x.Public
	}
	return 0
}

type SearchMessagesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*SearchMessage       `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	Count         int32                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchMessagesResponse) Reset() {
	*x = SearchMessagesResponse{}
	mi := &file_protos_search_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchMessagesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchMessagesResponse) ProtoMessage() {}

func (x *SearchMessagesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_search_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchMessagesResponse.ProtoReflect.Descriptor instead.
func (*SearchMessagesResponse) Descriptor() ([]byte, []int) {
	return file_protos_search_proto_rawDescGZIP(), []int{8}
}

func (x *SearchMessagesResponse) GetList() []*SearchMessage {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *SearchMessagesResponse) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type SearchFilesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Substr        string                 `protobuf:"bytes,1,opt,name=substr,proto3" json:"substr,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchFilesRequest) Reset() {
	*x = SearchFilesRequest{}
	mi := &file_protos_search_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchFilesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchFilesRequest) ProtoMessage() {}

func (x *SearchFilesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_search_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchFilesRequest.ProtoReflect.Descriptor instead.
func (*SearchFilesRequest) Descriptor() ([]byte, []int) {
	return file_protos_search_proto_rawDescGZIP(), []int{9}
}

func (x *SearchFilesRequest) GetSubstr() string {
	if x != nil {
		return x.Substr
	}
	return ""
}

func (x *SearchFilesRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type SearchFilesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*SearchFile          `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	Count         int32                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchFilesResponse) Reset() {
	*x = SearchFilesResponse{}
	mi := &file_protos_search_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchFilesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchFilesResponse) ProtoMessage() {}

func (x *SearchFilesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_search_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchFilesResponse.ProtoReflect.Descriptor instead.
func (*SearchFilesResponse) Descriptor() ([]byte, []int) {
	return file_protos_search_proto_rawDescGZIP(), []int{10}
}

func (x *SearchFilesResponse) GetList() []*SearchFile {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *SearchFilesResponse) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

var File_protos_search_proto protoreflect.FileDescriptor

const file_protos_search_proto_rawDesc = "" +
	"\n" +
	"\x13protos/search.proto\x12\tsearch.v1\"\xa0\x02\n" +
	"\x0eSearchSnapshot\x12@\n" +
	"\amessage\x18\x01 \x01(\v2$.search.v1.SearchMessageSnapshotItemH\x00R\amessage\x127\n" +
	"\x04file\x18\x02 \x01(\v2!.search.v1.SearchFileSnapshotItemH\x00R\x04file\x12=\n" +
	"\x06thread\x18\x03 \x01(\v2#.search.v1.SearchThreadSnapshotItemH\x00R\x06thread\x12L\n" +
	"\vtranslation\x18\x04 \x01(\v2(.search.v1.SearchTranslationSnapshotItemH\x00R\vtranslationB\x06\n" +
	"\x04Item\"\xda\x01\n" +
	"\x19SearchMessageSnapshotItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12\x12\n" +
	"\x04text\x18\x05 \x01(\tR\x04text\x12\x18\n" +
	"\aprivate\x18\x06 \x01(\bR\aprivate\x12\x1d\n" +
	"\n" +
	"created_at\x18\a \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\b \x01(\tR\tupdatedAt\"\xf7\x01\n" +
	"\x16SearchFileSnapshotItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x12\n" +
	"\x04mime\x18\x04 \x01(\tR\x04mime\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\tR\tupdatedAt\x12\x12\n" +
	"\x04size\x18\a \x01(\x03R\x04size\x12\x18\n" +
	"\aprivate\x18\b \x01(\bR\aprivate\x12 \n" +
	"\vdescription\x18\t \x01(\tR\vdescription\"\xee\x01\n" +
	"\x18SearchThreadSnapshotItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12\x1b\n" +
	"\tparent_id\x18\x03 \x01(\x03R\bparentId\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12\x18\n" +
	"\aprivate\x18\x06 \x01(\bR\aprivate\x12\x1d\n" +
	"\n" +
	"created_at\x18\a \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\b \x01(\tR\tupdatedAt\"\xd3\x01\n" +
	"\x1dSearchTranslationSnapshotItem\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\x03R\tmessageId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12\x12\n" +
	"\x04lang\x18\x03 \x01(\tR\x04lang\x12\x12\n" +
	"\x04text\x18\x04 \x01(\tR\x04text\x12\x14\n" +
	"\x05title\x18\x05 \x01(\tR\x05title\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\a \x01(\tR\tupdatedAt\"\xce\x01\n" +
	"\rSearchMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12\x12\n" +
	"\x04text\x18\x05 \x01(\tR\x04text\x12\x18\n" +
	"\aprivate\x18\x06 \x01(\bR\aprivate\x12\x1d\n" +
	"\n" +
	"created_at\x18\a \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\b \x01(\tR\tupdatedAt\"\x87\x01\n" +
	"\n" +
	"SearchFile\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"created_at\x18\x04 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x05 \x01(\tR\tupdatedAt\"\xa0\x01\n" +
	"\x15SearchMessagesRequest\x12\x16\n" +
	"\x06substr\x18\x01 \x01(\tR\x06substr\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12 \n" +
	"\tthread_id\x18\x03 \x01(\x03H\x00R\bthreadId\x88\x01\x01\x12\x1b\n" +
	"\x06public\x18\x04 \x01(\x05H\x01R\x06public\x88\x01\x01B\f\n" +
	"\n" +
	"_thread_idB\t\n" +
	"\a_public\"\\\n" +
	"\x16SearchMessagesResponse\x12,\n" +
	"\x04list\x18\x01 \x03(\v2\x18.search.v1.SearchMessageR\x04list\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x05R\x05count\"E\n" +
	"\x12SearchFilesRequest\x12\x16\n" +
	"\x06substr\x18\x01 \x01(\tR\x06substr\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\"V\n" +
	"\x13SearchFilesResponse\x12)\n" +
	"\x04list\x18\x01 \x03(\v2\x15.search.v1.SearchFileR\x04list\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x05R\x05count2\xb1\x01\n" +
	"\x06Search\x12W\n" +
	"\x0eSearchMessages\x12 .search.v1.SearchMessagesRequest\x1a!.search.v1.SearchMessagesResponse\"\x00\x12N\n" +
	"\vSearchFiles\x12\x1d.search.v1.SearchFilesRequest\x1a\x1e.search.v1.SearchFilesResponse\"\x00B%Z#github.com/bd878/gallery/server/apib\x06proto3"

var (
	file_protos_search_proto_rawDescOnce sync.Once
	file_protos_search_proto_rawDescData []byte
)

func file_protos_search_proto_rawDescGZIP() []byte {
	file_protos_search_proto_rawDescOnce.Do(func() {
		file_protos_search_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protos_search_proto_rawDesc), len(file_protos_search_proto_rawDesc)))
	})
	return file_protos_search_proto_rawDescData
}

var file_protos_search_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_protos_search_proto_goTypes = []any{
	(*SearchSnapshot)(nil),                // 0: search.v1.SearchSnapshot
	(*SearchMessageSnapshotItem)(nil),     // 1: search.v1.SearchMessageSnapshotItem
	(*SearchFileSnapshotItem)(nil),        // 2: search.v1.SearchFileSnapshotItem
	(*SearchThreadSnapshotItem)(nil),      // 3: search.v1.SearchThreadSnapshotItem
	(*SearchTranslationSnapshotItem)(nil), // 4: search.v1.SearchTranslationSnapshotItem
	(*SearchMessage)(nil),                 // 5: search.v1.SearchMessage
	(*SearchFile)(nil),                    // 6: search.v1.SearchFile
	(*SearchMessagesRequest)(nil),         // 7: search.v1.SearchMessagesRequest
	(*SearchMessagesResponse)(nil),        // 8: search.v1.SearchMessagesResponse
	(*SearchFilesRequest)(nil),            // 9: search.v1.SearchFilesRequest
	(*SearchFilesResponse)(nil),           // 10: search.v1.SearchFilesResponse
}
var file_protos_search_proto_depIdxs = []int32{
	1,  // 0: search.v1.SearchSnapshot.message:type_name -> search.v1.SearchMessageSnapshotItem
	2,  // 1: search.v1.SearchSnapshot.file:type_name -> search.v1.SearchFileSnapshotItem
	3,  // 2: search.v1.SearchSnapshot.thread:type_name -> search.v1.SearchThreadSnapshotItem
	4,  // 3: search.v1.SearchSnapshot.translation:type_name -> search.v1.SearchTranslationSnapshotItem
	5,  // 4: search.v1.SearchMessagesResponse.list:type_name -> search.v1.SearchMessage
	6,  // 5: search.v1.SearchFilesResponse.list:type_name -> search.v1.SearchFile
	7,  // 6: search.v1.Search.SearchMessages:input_type -> search.v1.SearchMessagesRequest
	9,  // 7: search.v1.Search.SearchFiles:input_type -> search.v1.SearchFilesRequest
	8,  // 8: search.v1.Search.SearchMessages:output_type -> search.v1.SearchMessagesResponse
	10, // 9: search.v1.Search.SearchFiles:output_type -> search.v1.SearchFilesResponse
	8,  // [8:10] is the sub-list for method output_type
	6,  // [6:8] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_protos_search_proto_init() }
func file_protos_search_proto_init() {
	if File_protos_search_proto != nil {
		return
	}
	file_protos_search_proto_msgTypes[0].OneofWrappers = []any{
		(*SearchSnapshot_Message)(nil),
		(*SearchSnapshot_File)(nil),
		(*SearchSnapshot_Thread)(nil),
		(*SearchSnapshot_Translation)(nil),
	}
	file_protos_search_proto_msgTypes[7].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protos_search_proto_rawDesc), len(file_protos_search_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protos_search_proto_goTypes,
		DependencyIndexes: file_protos_search_proto_depIdxs,
		MessageInfos:      file_protos_search_proto_msgTypes,
	}.Build()
	File_protos_search_proto = out.File
	file_protos_search_proto_goTypes = nil
	file_protos_search_proto_depIdxs = nil
}
