// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.19.4
// source: protos/translations.proto

package api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Translations_SaveTranslation_FullMethodName   = "/translations.v1.Translations/SaveTranslation"
	Translations_UpdateTranslation_FullMethodName = "/translations.v1.Translations/UpdateTranslation"
	Translations_DeleteTranslation_FullMethodName = "/translations.v1.Translations/DeleteTranslation"
	Translations_ReadTranslation_FullMethodName   = "/translations.v1.Translations/ReadTranslation"
	Translations_ListTranslations_FullMethodName  = "/translations.v1.Translations/ListTranslations"
)

// TranslationsClient is the client API for Translations service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TranslationsClient interface {
	SaveTranslation(ctx context.Context, in *SaveTranslationRequest, opts ...grpc.CallOption) (*SaveTranslationResponse, error)
	UpdateTranslation(ctx context.Context, in *UpdateTranslationRequest, opts ...grpc.CallOption) (*UpdateTranslationResponse, error)
	DeleteTranslation(ctx context.Context, in *DeleteTranslationRequest, opts ...grpc.CallOption) (*DeleteTranslationResponse, error)
	ReadTranslation(ctx context.Context, in *ReadTranslationRequest, opts ...grpc.CallOption) (*ReadTranslationResponse, error)
	ListTranslations(ctx context.Context, in *ListTranslationsRequest, opts ...grpc.CallOption) (*ListTranslationsResponse, error)
}

type translationsClient struct {
	cc grpc.ClientConnInterface
}

func NewTranslationsClient(cc grpc.ClientConnInterface) TranslationsClient {
	return &translationsClient{cc}
}

func (c *translationsClient) SaveTranslation(ctx context.Context, in *SaveTranslationRequest, opts ...grpc.CallOption) (*SaveTranslationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SaveTranslationResponse)
	err := c.cc.Invoke(ctx, Translations_SaveTranslation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *translationsClient) UpdateTranslation(ctx context.Context, in *UpdateTranslationRequest, opts ...grpc.CallOption) (*UpdateTranslationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateTranslationResponse)
	err := c.cc.Invoke(ctx, Translations_UpdateTranslation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *translationsClient) DeleteTranslation(ctx context.Context, in *DeleteTranslationRequest, opts ...grpc.CallOption) (*DeleteTranslationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteTranslationResponse)
	err := c.cc.Invoke(ctx, Translations_DeleteTranslation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *translationsClient) ReadTranslation(ctx context.Context, in *ReadTranslationRequest, opts ...grpc.CallOption) (*ReadTranslationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReadTranslationResponse)
	err := c.cc.Invoke(ctx, Translations_ReadTranslation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *translationsClient) ListTranslations(ctx context.Context, in *ListTranslationsRequest, opts ...grpc.CallOption) (*ListTranslationsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListTranslationsResponse)
	err := c.cc.Invoke(ctx, Translations_ListTranslations_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TranslationsServer is the server API for Translations service.
// All implementations must embed UnimplementedTranslationsServer
// for forward compatibility.
type TranslationsServer interface {
	SaveTranslation(context.Context, *SaveTranslationRequest) (*SaveTranslationResponse, error)
	UpdateTranslation(context.Context, *UpdateTranslationRequest) (*UpdateTranslationResponse, error)
	DeleteTranslation(context.Context, *DeleteTranslationRequest) (*DeleteTranslationResponse, error)
	ReadTranslation(context.Context, *ReadTranslationRequest) (*ReadTranslationResponse, error)
	ListTranslations(context.Context, *ListTranslationsRequest) (*ListTranslationsResponse, error)
	mustEmbedUnimplementedTranslationsServer()
}

// UnimplementedTranslationsServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTranslationsServer struct{}

func (UnimplementedTranslationsServer) SaveTranslation(context.Context, *SaveTranslationRequest) (*SaveTranslationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SaveTranslation not implemented")
}
func (UnimplementedTranslationsServer) UpdateTranslation(context.Context, *UpdateTranslationRequest) (*UpdateTranslationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateTranslation not implemented")
}
func (UnimplementedTranslationsServer) DeleteTranslation(context.Context, *DeleteTranslationRequest) (*DeleteTranslationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteTranslation not implemented")
}
func (UnimplementedTranslationsServer) ReadTranslation(context.Context, *ReadTranslationRequest) (*ReadTranslationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReadTranslation not implemented")
}
func (UnimplementedTranslationsServer) ListTranslations(context.Context, *ListTranslationsRequest) (*ListTranslationsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListTranslations not implemented")
}
func (UnimplementedTranslationsServer) mustEmbedUnimplementedTranslationsServer() {}
func (UnimplementedTranslationsServer) testEmbeddedByValue()                      {}

// UnsafeTranslationsServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TranslationsServer will
// result in compilation errors.
type UnsafeTranslationsServer interface {
	mustEmbedUnimplementedTranslationsServer()
}

func RegisterTranslationsServer(s grpc.ServiceRegistrar, srv TranslationsServer) {
	// If the following call panics, it indicates UnimplementedTranslationsServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Translations_ServiceDesc, srv)
}

func _Translations_SaveTranslation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveTranslationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TranslationsServer).SaveTranslation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Translations_SaveTranslation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TranslationsServer).SaveTranslation(ctx, req.(*SaveTranslationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Translations_UpdateTranslation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateTranslationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TranslationsServer).UpdateTranslation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Translations_UpdateTranslation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TranslationsServer).UpdateTranslation(ctx, req.(*UpdateTranslationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Translations_DeleteTranslation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteTranslationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TranslationsServer).DeleteTranslation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Translations_DeleteTranslation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TranslationsServer).DeleteTranslation(ctx, req.(*DeleteTranslationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Translations_ReadTranslation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadTranslationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TranslationsServer).ReadTranslation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Translations_ReadTranslation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TranslationsServer).ReadTranslation(ctx, req.(*ReadTranslationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Translations_ListTranslations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTranslationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TranslationsServer).ListTranslations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Translations_ListTranslations_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TranslationsServer).ListTranslations(ctx, req.(*ListTranslationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Translations_ServiceDesc is the grpc.ServiceDesc for Translations service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Translations_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "translations.v1.Translations",
	HandlerType: (*TranslationsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SaveTranslation",
			Handler:    _Translations_SaveTranslation_Handler,
		},
		{
			MethodName: "UpdateTranslation",
			Handler:    _Translations_UpdateTranslation_Handler,
		},
		{
			MethodName: "DeleteTranslation",
			Handler:    _Translations_DeleteTranslation_Handler,
		},
		{
			MethodName: "ReadTranslation",
			Handler:    _Translations_ReadTranslation_Handler,
		},
		{
			MethodName: "ListTranslations",
			Handler:    _Translations_ListTranslations_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protos/translations.proto",
}
