// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion7

// TranslationsClient is the client API for Translations service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TranslationsClient interface {
	SaveTranslation(ctx context.Context, in *SaveTranslationRequest, opts ...grpc.CallOption) (*SaveTranslationResponse, error)
	UpdateTranslation(ctx context.Context, in *UpdateTranslationRequest, opts ...grpc.CallOption) (*UpdateTranslationResponse, error)
	DeleteTranslation(ctx context.Context, in *DeleteTranslationRequest, opts ...grpc.CallOption) (*DeleteTranslationResponse, error)
	ReadTranslation(ctx context.Context, in *ReadTranslationRequest, opts ...grpc.CallOption) (*ReadTranslationResponse, error)
	ListTranslations(ctx context.Context, in *ListTranslationsRequest, opts ...grpc.CallOption) (*ListTranslationsResponse, error)
}

type translationsClient struct {
	cc grpc.ClientConnInterface
}

func NewTranslationsClient(cc grpc.ClientConnInterface) TranslationsClient {
	return &translationsClient{cc}
}

func (c *translationsClient) SaveTranslation(ctx context.Context, in *SaveTranslationRequest, opts ...grpc.CallOption) (*SaveTranslationResponse, error) {
	out := new(SaveTranslationResponse)
	err := c.cc.Invoke(ctx, "/translations.v1.Translations/SaveTranslation", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *translationsClient) UpdateTranslation(ctx context.Context, in *UpdateTranslationRequest, opts ...grpc.CallOption) (*UpdateTranslationResponse, error) {
	out := new(UpdateTranslationResponse)
	err := c.cc.Invoke(ctx, "/translations.v1.Translations/UpdateTranslation", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *translationsClient) DeleteTranslation(ctx context.Context, in *DeleteTranslationRequest, opts ...grpc.CallOption) (*DeleteTranslationResponse, error) {
	out := new(DeleteTranslationResponse)
	err := c.cc.Invoke(ctx, "/translations.v1.Translations/DeleteTranslation", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *translationsClient) ReadTranslation(ctx context.Context, in *ReadTranslationRequest, opts ...grpc.CallOption) (*ReadTranslationResponse, error) {
	out := new(ReadTranslationResponse)
	err := c.cc.Invoke(ctx, "/translations.v1.Translations/ReadTranslation", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *translationsClient) ListTranslations(ctx context.Context, in *ListTranslationsRequest, opts ...grpc.CallOption) (*ListTranslationsResponse, error) {
	out := new(ListTranslationsResponse)
	err := c.cc.Invoke(ctx, "/translations.v1.Translations/ListTranslations", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TranslationsServer is the server API for Translations service.
// All implementations must embed UnimplementedTranslationsServer
// for forward compatibility
type TranslationsServer interface {
	SaveTranslation(context.Context, *SaveTranslationRequest) (*SaveTranslationResponse, error)
	UpdateTranslation(context.Context, *UpdateTranslationRequest) (*UpdateTranslationResponse, error)
	DeleteTranslation(context.Context, *DeleteTranslationRequest) (*DeleteTranslationResponse, error)
	ReadTranslation(context.Context, *ReadTranslationRequest) (*ReadTranslationResponse, error)
	ListTranslations(context.Context, *ListTranslationsRequest) (*ListTranslationsResponse, error)
	mustEmbedUnimplementedTranslationsServer()
}

// UnimplementedTranslationsServer must be embedded to have forward compatible implementations.
type UnimplementedTranslationsServer struct {
}

func (UnimplementedTranslationsServer) SaveTranslation(context.Context, *SaveTranslationRequest) (*SaveTranslationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SaveTranslation not implemented")
}
func (UnimplementedTranslationsServer) UpdateTranslation(context.Context, *UpdateTranslationRequest) (*UpdateTranslationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateTranslation not implemented")
}
func (UnimplementedTranslationsServer) DeleteTranslation(context.Context, *DeleteTranslationRequest) (*DeleteTranslationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteTranslation not implemented")
}
func (UnimplementedTranslationsServer) ReadTranslation(context.Context, *ReadTranslationRequest) (*ReadTranslationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReadTranslation not implemented")
}
func (UnimplementedTranslationsServer) ListTranslations(context.Context, *ListTranslationsRequest) (*ListTranslationsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListTranslations not implemented")
}
func (UnimplementedTranslationsServer) mustEmbedUnimplementedTranslationsServer() {}

// UnsafeTranslationsServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TranslationsServer will
// result in compilation errors.
type UnsafeTranslationsServer interface {
	mustEmbedUnimplementedTranslationsServer()
}

func RegisterTranslationsServer(s *grpc.Server, srv TranslationsServer) {
	s.RegisterService(&_Translations_serviceDesc, srv)
}

func _Translations_SaveTranslation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveTranslationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TranslationsServer).SaveTranslation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/translations.v1.Translations/SaveTranslation",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TranslationsServer).SaveTranslation(ctx, req.(*SaveTranslationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Translations_UpdateTranslation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateTranslationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TranslationsServer).UpdateTranslation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/translations.v1.Translations/UpdateTranslation",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TranslationsServer).UpdateTranslation(ctx, req.(*UpdateTranslationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Translations_DeleteTranslation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteTranslationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TranslationsServer).DeleteTranslation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/translations.v1.Translations/DeleteTranslation",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TranslationsServer).DeleteTranslation(ctx, req.(*DeleteTranslationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Translations_ReadTranslation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadTranslationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TranslationsServer).ReadTranslation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/translations.v1.Translations/ReadTranslation",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TranslationsServer).ReadTranslation(ctx, req.(*ReadTranslationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Translations_ListTranslations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTranslationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TranslationsServer).ListTranslations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/translations.v1.Translations/ListTranslations",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TranslationsServer).ListTranslations(ctx, req.(*ListTranslationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Translations_serviceDesc = grpc.ServiceDesc{
	ServiceName: "translations.v1.Translations",
	HandlerType: (*TranslationsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SaveTranslation",
			Handler:    _Translations_SaveTranslation_Handler,
		},
		{
			MethodName: "UpdateTranslation",
			Handler:    _Translations_UpdateTranslation_Handler,
		},
		{
			MethodName: "DeleteTranslation",
			Handler:    _Translations_DeleteTranslation_Handler,
		},
		{
			MethodName: "ReadTranslation",
			Handler:    _Translations_ReadTranslation_Handler,
		},
		{
			MethodName: "ListTranslations",
			Handler:    _Translations_ListTranslations_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protos/translations.proto",
}
