// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.19.4
// source: protos/translations_events.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TranslationCreated struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Lang          string                 `protobuf:"bytes,2,opt,name=lang,proto3" json:"lang,omitempty"`
	Text          string                 `protobuf:"bytes,3,opt,name=text,proto3" json:"text,omitempty"`
	Title         string                 `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	UserId        int64                  `protobuf:"varint,5,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TranslationCreated) Reset() {
	*x = TranslationCreated{}
	mi := &file_protos_translations_events_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TranslationCreated) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TranslationCreated) ProtoMessage() {}

func (x *TranslationCreated) ProtoReflect() protoreflect.Message {
	mi := &file_protos_translations_events_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TranslationCreated.ProtoReflect.Descriptor instead.
func (*TranslationCreated) Descriptor() ([]byte, []int) {
	return file_protos_translations_events_proto_rawDescGZIP(), []int{0}
}

func (x *TranslationCreated) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *TranslationCreated) GetLang() string {
	if x != nil {
		return x.Lang
	}
	return ""
}

func (x *TranslationCreated) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *TranslationCreated) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *TranslationCreated) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *TranslationCreated) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *TranslationCreated) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type TranslationDeleted struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Lang          string                 `protobuf:"bytes,2,opt,name=lang,proto3" json:"lang,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TranslationDeleted) Reset() {
	*x = TranslationDeleted{}
	mi := &file_protos_translations_events_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TranslationDeleted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TranslationDeleted) ProtoMessage() {}

func (x *TranslationDeleted) ProtoReflect() protoreflect.Message {
	mi := &file_protos_translations_events_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TranslationDeleted.ProtoReflect.Descriptor instead.
func (*TranslationDeleted) Descriptor() ([]byte, []int) {
	return file_protos_translations_events_proto_rawDescGZIP(), []int{1}
}

func (x *TranslationDeleted) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *TranslationDeleted) GetLang() string {
	if x != nil {
		return x.Lang
	}
	return ""
}

type TranslationUpdated struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Lang          string                 `protobuf:"bytes,2,opt,name=lang,proto3" json:"lang,omitempty"`
	Text          *string                `protobuf:"bytes,3,opt,name=text,proto3,oneof" json:"text,omitempty"`
	Title         *string                `protobuf:"bytes,4,opt,name=title,proto3,oneof" json:"title,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TranslationUpdated) Reset() {
	*x = TranslationUpdated{}
	mi := &file_protos_translations_events_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TranslationUpdated) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TranslationUpdated) ProtoMessage() {}

func (x *TranslationUpdated) ProtoReflect() protoreflect.Message {
	mi := &file_protos_translations_events_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TranslationUpdated.ProtoReflect.Descriptor instead.
func (*TranslationUpdated) Descriptor() ([]byte, []int) {
	return file_protos_translations_events_proto_rawDescGZIP(), []int{2}
}

func (x *TranslationUpdated) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *TranslationUpdated) GetLang() string {
	if x != nil {
		return x.Lang
	}
	return ""
}

func (x *TranslationUpdated) GetText() string {
	if x != nil && x.Text != nil {
		return *x.Text
	}
	return ""
}

func (x *TranslationUpdated) GetTitle() string {
	if x != nil && x.Title != nil {
		return *x.Title
	}
	return ""
}

func (x *TranslationUpdated) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

var File_protos_translations_events_proto protoreflect.FileDescriptor

const file_protos_translations_events_proto_rawDesc = "" +
	"\n" +
	" protos/translations_events.proto\x12\x16translations_events.v1\"\xb9\x01\n" +
	"\x12TranslationCreated\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04lang\x18\x02 \x01(\tR\x04lang\x12\x12\n" +
	"\x04text\x18\x03 \x01(\tR\x04text\x12\x14\n" +
	"\x05title\x18\x04 \x01(\tR\x05title\x12\x17\n" +
	"\auser_id\x18\x05 \x01(\x03R\x06userId\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\a \x01(\tR\tupdatedAt\"8\n" +
	"\x12TranslationDeleted\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04lang\x18\x02 \x01(\tR\x04lang\"\x9e\x01\n" +
	"\x12TranslationUpdated\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04lang\x18\x02 \x01(\tR\x04lang\x12\x17\n" +
	"\x04text\x18\x03 \x01(\tH\x00R\x04text\x88\x01\x01\x12\x19\n" +
	"\x05title\x18\x04 \x01(\tH\x01R\x05title\x88\x01\x01\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x05 \x01(\tR\tupdatedAtB\a\n" +
	"\x05_textB\b\n" +
	"\x06_titleB%Z#github.com/bd878/gallery/server/apib\x06proto3"

var (
	file_protos_translations_events_proto_rawDescOnce sync.Once
	file_protos_translations_events_proto_rawDescData []byte
)

func file_protos_translations_events_proto_rawDescGZIP() []byte {
	file_protos_translations_events_proto_rawDescOnce.Do(func() {
		file_protos_translations_events_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protos_translations_events_proto_rawDesc), len(file_protos_translations_events_proto_rawDesc)))
	})
	return file_protos_translations_events_proto_rawDescData
}

var file_protos_translations_events_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_protos_translations_events_proto_goTypes = []any{
	(*TranslationCreated)(nil), // 0: translations_events.v1.TranslationCreated
	(*TranslationDeleted)(nil), // 1: translations_events.v1.TranslationDeleted
	(*TranslationUpdated)(nil), // 2: translations_events.v1.TranslationUpdated
}
var file_protos_translations_events_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_protos_translations_events_proto_init() }
func file_protos_translations_events_proto_init() {
	if File_protos_translations_events_proto != nil {
		return
	}
	file_protos_translations_events_proto_msgTypes[2].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protos_translations_events_proto_rawDesc), len(file_protos_translations_events_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protos_translations_events_proto_goTypes,
		DependencyIndexes: file_protos_translations_events_proto_depIdxs,
		MessageInfos:      file_protos_translations_events_proto_msgTypes,
	}.Build()
	File_protos_translations_events_proto = out.File
	file_protos_translations_events_proto_goTypes = nil
	file_protos_translations_events_proto_depIdxs = nil
}
