syntax = "proto3";

package billing.v1;

import "protos/distributed.proto";

option go_package = "github.com/bd878/gallery/server/api";

service Billing {
	rpc Apply(distributed.v1.Command) returns (distributed.v1.CommandResponse) {}
	rpc GetInvoice(GetInvoiceRequest) returns (GetInvoiceResponse) {}
	rpc GetPayment(GetPaymentRequest) returns (GetPaymentResponse) {}
}

message BillingSnapshot {
	oneof Item {
		InvoiceSnapshotItem invoice = 1;
		PaymentSnapshotItem payment = 2;
	}
}

message InvoiceSnapshotItem {
	string    id = 1;
	int64     user_id = 2;
	string    status = 3;
	int64     total = 4;
	string    created_at = 5;
	string    updated_at = 6;
	bytes     cart = 7;
	optional bytes metadata = 8;
}

message PaymentSnapshotItem {
	int64     id = 1;
	int64     user_id = 2;
	string    invoice_id = 3;
	string    status = 4;
	string    currency = 5;
	int64     total = 6;
	string    created_at = 7;
	string    updated_at = 8;
	optional bytes metadata = 9;
}

message Invoice {
	string    id = 1;
	int64     user_id = 2;
	string    status = 3;
	int64     total = 4;
	string    created_at = 5;
	string    updated_at = 6;
	Cart      cart = 7;
	optional bytes metadata = 8;
}

message Payment {
	int64     id = 1;
	int64     user_id = 2;
	string    invoice_id = 3;
	string    status = 4;
	string    currency = 5;
	int64     total = 6;
	string    created_at = 7;
	string    updated_at = 8;
	optional bytes metadata = 9;
}

message Cart {
	repeated CartItem items = 1;
}

message CartItem {
	oneof Item {
		Premium premium = 1;
	}
}

message Premium {
	string expires_at = 1;
	int64  cost = 2;
	int64  discount = 3;
	string currency = 4;
}

message GetInvoiceRequest {
	string id = 1;
	int64  user_id = 2;
}

message GetInvoiceResponse {
	Invoice invoice = 1;
}

message GetPaymentRequest {
	int64   id = 1;
	int64   user_id = 2;
}

message GetPaymentResponse {
	Payment payment = 1;
}