syntax = "proto3";

package comments.v1;

import "protos/distributed.proto";

option go_package = "github.com/bd878/gallery/server/api/comments";

service Comments {
	rpc Apply(distributed.v1.Command) returns (distributed.v1.CommandResponse);
	rpc ReadComment(ReadCommentRequest) returns (ReadCommentResponse);
	rpc ListComments(ListCommentsRequest) returns (ListCommentsResponse);
}

message CommentSnapshotItem {
	int64     id = 1;
	int64     message_id = 2;
	int64     user_id = 3;
	string    text = 4;
	string    created_at = 5;
	string    updated_at = 6;
	optional bytes metadata = 7;
}

message Comment {
	int64     id = 1;
	int64     message_id = 2;
	int64     user_id = 3;
	string    text = 4;
	string    created_at = 5;
	string    updated_at = 6;
	optional bytes metadata = 7;
}

message CommentsList {
	repeated Comment comments = 1;
	bool     is_last_page = 2;
	bool     is_first_page = 3;
	int32    total = 4;
	int32    count = 5;
}

message ListCommentsRequest {
	int32     limit = 1;
	int32     offset = 2;
	bool      asc = 3;
	optional int64 message_id = 4;
	optional int64 user_id = 5;
	optional string name = 6;
}

message ListCommentsResponse {
	repeated Comment comments = 1;
	bool     is_last_page = 2;
	bool     is_first_page = 3;
	int32    total = 4;
	int32    count = 5;
}

message ReadCommentRequest {
	int64      id = 1;
	int64      user_id = 2;
}

message ReadCommentResponse {
	Comment comment = 1;
}
