syntax = "proto3";

package translations.v1;

import "protos/distributed.proto";

option go_package = "github.com/bd878/gallery/server/api/translations";

service Translations {
	rpc Apply(distributed.v1.Command) returns (distributed.v1.CommandResponse);
	rpc ReadTranslation(ReadTranslationRequest) returns (ReadTranslationResponse) {}
	rpc ListTranslations(ListTranslationsRequest) returns (ListTranslationsResponse) {}
}

message TranslationSnapshotItem {
	int64     id = 1;
	string    lang = 2;
	string    text = 3;
	string    title = 4;
	string    created_at = 5;
	string    updated_at = 6;
}

message Translation {
	int64     id = 1;
	string    lang = 2;
	string    text = 3;
	string    title = 4;
	string    created_at = 5;
	string    updated_at = 6;
}

message TranslationPreview {
	int64     id = 1;
	string    lang = 2;
	string    title = 3;
	string    created_at = 4;
	string    updated_at = 5;
}

message ReadTranslationRequest {
	int64     user_id = 1;
	int64     id = 2;
	string    lang = 3;
	optional string  name = 4;
}

message ReadTranslationResponse {
	Translation translation = 1;
}

message ListTranslationsRequest {
	int64     id = 1;
	string    name = 2;
	int64     user_id = 3;
}

message ListTranslationsResponse {
	repeated Translation translations = 1;
}
