syntax = "proto3";

package users.v1;

import "protos/distributed.proto";

option go_package = "github.com/bd878/gallery/server/api/users";

service Users {
	rpc Apply(distributed.v1.Command) returns (distributed.v1.CommandResponse) {}
	rpc FindUser(FindUserRequest) returns (User);
	rpc GetUser(GetUserRequest) returns (User);
}

message User {
	int64     id = 1;
	string    login = 2;
	string    hashed_password = 3;
	string    created_at = 4;
	string    updated_at = 5;
	bool      is_premium = 6;
	optional bytes metadata = 7;
}

message UsersSnapshot {
	oneof Item {
		UserSnapshotItem user = 1;
		PremiumSnapshotItem premium = 2;
	}
}

message UserSnapshotItem {
	int64 id = 1;
	string login = 2;
	string hashed_password = 3;
	string created_at = 4;
	string updated_at = 5;
	optional bytes metadata = 6;
}

message PremiumSnapshotItem {
	int64 id = 1;
	string invoice_id = 2;
	string created_at = 3;
	string expires_at = 4;
}

message GetUserRequest {
	int64     id = 1;
}

message FindUserRequest {
	string login = 1;
}
