server {
	listen			  91.201.53.146:80;
	server_name		  stage.lesnotes.space;
	return 301		  https://stage.lesnotes.space$request_uri;

#	location /.well-known/acme-challenge/ {
#		alias /srv/gallery/;
#		autoindex off;
#	}
}

server {
	listen			  91.201.53.146:80;
	server_name		  lesnotes.space;
	return 301		  https://lesnotes.space$request_uri;

#	location /.well-known/acme-challenge/ {
#		alias /srv/gallery/;
#		autoindex off;
#	}
}

# server {
#	listen			  91.201.53.146:80;
#	server_name		  bot.lesnotes.space;
#
#	location /.well-known/acme-challenge/ {
#		alias /srv/bot/;
#		autoindex off;
#	}
#}

server {
	listen                    91.201.53.146:443 ssl;
	server_name               stage.lesnotes.space;
	ssl_certificate	          /srv/gallery/stage/.certs/fullchain.pem;
	ssl_certificate_key       /srv/gallery/stage/.certs/privkey.pem;
	ssl_session_cache         shared:SSL:10m;
	ssl_session_timeout       10m;

	keepalive_timeout   70;

	location /messages/v1/ {
		proxy_pass http://192.168.10.3:7101;
	}
	location /translations/v1/ {
		proxy_pass http://192.168.10.3:7101;
	}

	location /messages/v1/send {
		client_max_body_size 50m;
		proxy_pass http://192.168.10.3:7101;
	}

	location /messages/v2/ {
		proxy_pass http://192.168.10.3:7101;
	}
	location /translations/v2/ {
		proxy_pass http://192.168.10.3:7101;
	}

	location /messages/v2/send {
		client_max_body_size 50m;
		proxy_pass http://192.168.10.3:7101;
	}

	location /users/v2/ {
		proxy_pass http://192.168.10.3:7121;
	}
	location /users/v1/ {
		proxy_pass http://192.168.10.3:7121;
	}
	location /files/v1/ {
		client_max_body_size 50m;
		proxy_pass http://192.168.10.6:8182;
	}
	location /files/v2/ {
		client_max_body_size 50m;
		proxy_pass http://192.168.10.6:8182;
	}
	location /search/v1 {
		proxy_pass http://192.168.10.3:7111;
	}
	location /search/v2 {
		proxy_pass http://192.168.10.3:7111;
	}
	location /threads/v1 {
		proxy_pass http://192.168.10.3:7141;
	}
	location /threads/v2 {
		proxy_pass http://192.168.10.3:7141;
	}
	location /billing/v1 {
		proxy_pass http://192.168.10.3:7151;
	}
	location /billing/v2 {
		proxy_pass http://192.168.10.3:7151;
	}
	location / {
		proxy_pass http://192.168.10.3:8080;
	}
}

server {
	listen                    91.201.53.146:443 ssl;
	server_name               lesnotes.space;
	ssl_certificate	          /srv/gallery/prod/.certs/fullchain.pem;
	ssl_certificate_key       /srv/gallery/prod/.certs/privkey.pem;
	ssl_session_cache         shared:SSL:10m;
	ssl_session_timeout       10m;

	keepalive_timeout   70;

	location /messages/v1/ {
		proxy_pass http://192.168.10.2:8083;
	}
	location /translations/v1/ {
		proxy_pass http://192.168.10.2:8083;
	}

	location /messages/v1/send {
		client_max_body_size 50m;
		proxy_pass http://192.168.10.2:8083;
	}
	location /messages/v2/ {
		proxy_pass http://192.168.10.2:8083;
	}
	location /translations/v2/ {
		proxy_pass http://192.168.10.2:8083;
	}

	location /messages/v2/send {
		client_max_body_size 50m;
		proxy_pass http://192.168.10.2:8083;
	}

	location /users/v2/ {
		proxy_pass http://192.168.10.2:8084;
	}
	location /users/v1/ {
		proxy_pass http://192.168.10.2:8084;
	}
	location /search/v1/ {
		proxy_pass http://192.168.10.2:8090;
	}
	location /search/v2/ {
		proxy_pass http://192.168.10.2:8090;
	}
	location /files/v1/ {
		client_max_body_size 50m;
		proxy_pass http://192.168.10.5:8082;
	}
	location /files/v2/ {
		client_max_body_size 50m;
		proxy_pass http://192.168.10.5:8082;
	}
	location /threads/v1 {
		proxy_pass http://192.168.10.2:8085;
	}
	location /threads/v2 {
		proxy_pass http://192.168.10.2:8085;
	}
	location /billing/v1 {
		proxy_pass http://192.168.10.2:8088;
	}
	location /billing/v2 {
		proxy_pass http://192.168.10.2:8088;
	}
	location / {
		proxy_pass http://192.168.10.2:8081;
	}
}
