[hosts]
gallery-prod-4 ansible_host=192.168.10.40 ansible_become_password="{{ snd_become_pass }}"
gallery-prod-3 ansible_host=192.168.10.30 ansible_become_password="{{ snd_become_pass }}"
gallery-prod ansible_host=192.168.10.10 ansible_become_password="{{ snd_become_pass }}"

[machines]
nlp ansible_host=185.180.196.21 ansible_become_password="{{ host_become_pass }}"

[other]
infra ansible_host=192.168.10.11 ansible_become_password="{{ snd_become_pass }}"
gallery-prod-files ansible_host=192.168.10.50 ansible_become_password="{{ snd_become_pass }}"

