SET client_min_messages TO WARNING;

BEGIN;

\echo `# Configure database privileges`

REVOKE ALL ON LANGUAGE plpgsql FROM PUBLIC;
REVOKE ALL ON SCHEMA public FROM PUBLIC;
REVOKE ALL ON SCHEMA information_schema FROM PUBLIC;

REVOKE ALL ON pg_catalog.pg_auth_members FROM PUBLIC;
REVOKE ALL ON pg_catalog.pg_group FROM PUBLIC;
REVOKE ALL ON pg_catalog.pg_roles FROM PUBLIC;
REVOKE ALL ON pg_catalog.pg_user FROM PUBLIC;
REVOKE ALL ON pg_catalog.pg_user_mappings FROM PUBLIC;

CREATE USER lesnotes_admin WITH ENCRYPTED PASSWORD 'SCRAM-SHA-256$4096:W1xbnJKlqbNL0ywS2IjAOg==$hR59oE5bmL0bqxwzIToxBMsND5UxvXyqc65gUskqcXs=:/8phWf68FyKDBAfODNlbAJCjxB4hiE16vrS1QNGy/cA=';

GRANT ALL ON SCHEMA information_schema TO lesnotes_admin;
GRANT ALL PRIVILEGES ON SCHEMA public TO lesnotes_admin;

GRANT SELECT ON pg_catalog.pg_roles TO lesnotes_admin;
GRANT SELECT ON pg_catalog.pg_user TO lesnotes_admin;

ALTER DEFAULT PRIVILEGES REVOKE ALL ON ROUTINES FROM PUBLIC;
ALTER DEFAULT PRIVILEGES REVOKE ALL ON SCHEMAS FROM PUBLIC;
ALTER DEFAULT PRIVILEGES REVOKE ALL ON SEQUENCES FROM PUBLIC;
ALTER DEFAULT PRIVILEGES REVOKE ALL ON TABLES FROM PUBLIC;
ALTER DEFAULT PRIVILEGES REVOKE ALL ON TYPES FROM PUBLIC;

COMMIT;
