[hosts]
gallery-stage-4 ansible_host=192.168.10.140 ansible_become_password="{{ snd_become_pass }}"
gallery-stage-3 ansible_host=192.168.10.130 ansible_become_password="{{ snd_become_pass }}"
gallery-stage ansible_host=192.168.10.110 ansible_become_password="{{ snd_become_pass }}"

[machines]
kirschen ansible_host=213.189.219.229 ansible_become_password="{{ host_become_pass }}" ansible_become_method="su" ansible_become_exe="sudo su -"
schwarzwald ansible_host=91.201.53.146 ansible_become_password="{{ host_become_pass }}"
sonnenschein ansible_host=91.226.81.147 ansible_become_password="{{ host_become_pass }}" ansible_become_method="su" ansible_become_exe="sudo su -"

[other]
infra ansible_host=192.168.10.111 ansible_become_password="{{ snd_become_pass }}"

