[hosts]
gallery-stage-4 ansible_host=192.168.10.140 ansible_become_password="{{ snd_become_pass }}"
gallery-stage-3 ansible_host=192.168.10.130 ansible_become_password="{{ snd_become_pass }}"
gallery-stage ansible_host=192.168.10.3 ansible_become_password="{{ snd_become_pass }}"

[test]
gallery-stage-4
