// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.19.4
// source: server/internal/snapshot/sqlite/commands.proto

package sqlite

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RestoreCommand struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BackupFilePath string `protobuf:"bytes,1,opt,name=backup_file_path,json=backupFilePath,proto3" json:"backup_file_path,omitempty"`
}

func (x *RestoreCommand) Reset() {
	*x = RestoreCommand{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_internal_snapshot_sqlite_commands_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RestoreCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestoreCommand) ProtoMessage() {}

func (x *RestoreCommand) ProtoReflect() protoreflect.Message {
	mi := &file_server_internal_snapshot_sqlite_commands_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestoreCommand.ProtoReflect.Descriptor instead.
func (*RestoreCommand) Descriptor() ([]byte, []int) {
	return file_server_internal_snapshot_sqlite_commands_proto_rawDescGZIP(), []int{0}
}

func (x *RestoreCommand) GetBackupFilePath() string {
	if x != nil {
		return x.BackupFilePath
	}
	return ""
}

var File_server_internal_snapshot_sqlite_commands_proto protoreflect.FileDescriptor

var file_server_internal_snapshot_sqlite_commands_proto_rawDesc = []byte{
	0x0a, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61,
	0x6c, 0x2f, 0x73, 0x6e, 0x61, 0x70, 0x73, 0x68, 0x6f, 0x74, 0x2f, 0x73, 0x71, 0x6c, 0x69, 0x74,
	0x65, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0x3a, 0x0a, 0x0e, 0x52, 0x65, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x43, 0x6f, 0x6d, 0x6d, 0x61,
	0x6e, 0x64, 0x12, 0x28, 0x0a, 0x10, 0x62, 0x61, 0x63, 0x6b, 0x75, 0x70, 0x5f, 0x66, 0x69, 0x6c,
	0x65, 0x5f, 0x70, 0x61, 0x74, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x62, 0x61,
	0x63, 0x6b, 0x75, 0x70, 0x46, 0x69, 0x6c, 0x65, 0x50, 0x61, 0x74, 0x68, 0x42, 0x3a, 0x5a, 0x38,
	0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x62, 0x64, 0x38, 0x37, 0x38,
	0x2f, 0x67, 0x61, 0x6c, 0x6c, 0x65, 0x72, 0x79, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2f,
	0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x73, 0x6e, 0x61, 0x70, 0x73, 0x68, 0x6f,
	0x74, 0x2f, 0x73, 0x71, 0x6c, 0x69, 0x74, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_server_internal_snapshot_sqlite_commands_proto_rawDescOnce sync.Once
	file_server_internal_snapshot_sqlite_commands_proto_rawDescData = file_server_internal_snapshot_sqlite_commands_proto_rawDesc
)

func file_server_internal_snapshot_sqlite_commands_proto_rawDescGZIP() []byte {
	file_server_internal_snapshot_sqlite_commands_proto_rawDescOnce.Do(func() {
		file_server_internal_snapshot_sqlite_commands_proto_rawDescData = protoimpl.X.CompressGZIP(file_server_internal_snapshot_sqlite_commands_proto_rawDescData)
	})
	return file_server_internal_snapshot_sqlite_commands_proto_rawDescData
}

var file_server_internal_snapshot_sqlite_commands_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_server_internal_snapshot_sqlite_commands_proto_goTypes = []interface{}{
	(*RestoreCommand)(nil), // 0: RestoreCommand
}
var file_server_internal_snapshot_sqlite_commands_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_server_internal_snapshot_sqlite_commands_proto_init() }
func file_server_internal_snapshot_sqlite_commands_proto_init() {
	if File_server_internal_snapshot_sqlite_commands_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_server_internal_snapshot_sqlite_commands_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RestoreCommand); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_server_internal_snapshot_sqlite_commands_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_server_internal_snapshot_sqlite_commands_proto_goTypes,
		DependencyIndexes: file_server_internal_snapshot_sqlite_commands_proto_depIdxs,
		MessageInfos:      file_server_internal_snapshot_sqlite_commands_proto_msgTypes,
	}.Build()
	File_server_internal_snapshot_sqlite_commands_proto = out.File
	file_server_internal_snapshot_sqlite_commands_proto_rawDesc = nil
	file_server_internal_snapshot_sqlite_commands_proto_goTypes = nil
	file_server_internal_snapshot_sqlite_commands_proto_depIdxs = nil
}
