all : meta.proto
	protoc \
		--proto_path=../../../../ \
		--go_out=. \
		--go_opt=paths=import \
		--go_opt=module="github.com/bd878/gallery/server/internal/snapshot/sqlite" \
		server/internal/snapshot/sqlite/meta.proto