// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.19.4
// source: messages/internal/controller/distributed/commands.proto

package distributed

import (
	api "github.com/bd878/gallery/server/api"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AppendCommand struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message *api.Message `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *AppendCommand) Reset() {
	*x = AppendCommand{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_internal_controller_distributed_commands_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AppendCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppendCommand) ProtoMessage() {}

func (x *AppendCommand) ProtoReflect() protoreflect.Message {
	mi := &file_messages_internal_controller_distributed_commands_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppendCommand.ProtoReflect.Descriptor instead.
func (*AppendCommand) Descriptor() ([]byte, []int) {
	return file_messages_internal_controller_distributed_commands_proto_rawDescGZIP(), []int{0}
}

func (x *AppendCommand) GetMessage() *api.Message {
	if x != nil {
		return x.Message
	}
	return nil
}

type AppendCommandResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *AppendCommandResult) Reset() {
	*x = AppendCommandResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_internal_controller_distributed_commands_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AppendCommandResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppendCommandResult) ProtoMessage() {}

func (x *AppendCommandResult) ProtoReflect() protoreflect.Message {
	mi := &file_messages_internal_controller_distributed_commands_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppendCommandResult.ProtoReflect.Descriptor instead.
func (*AppendCommandResult) Descriptor() ([]byte, []int) {
	return file_messages_internal_controller_distributed_commands_proto_rawDescGZIP(), []int{1}
}

func (x *AppendCommandResult) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type UpdateCommand struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id            int32  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        int32  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	FileId        int32  `protobuf:"varint,3,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	Text          string `protobuf:"bytes,4,opt,name=text,proto3" json:"text,omitempty"`
	UpdateUtcNano int64  `protobuf:"varint,5,opt,name=update_utc_nano,json=updateUtcNano,proto3" json:"update_utc_nano,omitempty"`
	Private       int32  `protobuf:"varint,6,opt,name=private,proto3" json:"private,omitempty"`
}

func (x *UpdateCommand) Reset() {
	*x = UpdateCommand{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_internal_controller_distributed_commands_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCommand) ProtoMessage() {}

func (x *UpdateCommand) ProtoReflect() protoreflect.Message {
	mi := &file_messages_internal_controller_distributed_commands_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCommand.ProtoReflect.Descriptor instead.
func (*UpdateCommand) Descriptor() ([]byte, []int) {
	return file_messages_internal_controller_distributed_commands_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateCommand) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateCommand) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UpdateCommand) GetFileId() int32 {
	if x != nil {
		return x.FileId
	}
	return 0
}

func (x *UpdateCommand) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *UpdateCommand) GetUpdateUtcNano() int64 {
	if x != nil {
		return x.UpdateUtcNano
	}
	return 0
}

func (x *UpdateCommand) GetPrivate() int32 {
	if x != nil {
		return x.Private
	}
	return 0
}

type UpdateCommandResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UpdateUtcNano int64 `protobuf:"varint,1,opt,name=update_utc_nano,json=updateUtcNano,proto3" json:"update_utc_nano,omitempty"`
	Private       bool  `protobuf:"varint,2,opt,name=private,proto3" json:"private,omitempty"`
}

func (x *UpdateCommandResult) Reset() {
	*x = UpdateCommandResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_internal_controller_distributed_commands_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateCommandResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCommandResult) ProtoMessage() {}

func (x *UpdateCommandResult) ProtoReflect() protoreflect.Message {
	mi := &file_messages_internal_controller_distributed_commands_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCommandResult.ProtoReflect.Descriptor instead.
func (*UpdateCommandResult) Descriptor() ([]byte, []int) {
	return file_messages_internal_controller_distributed_commands_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateCommandResult) GetUpdateUtcNano() int64 {
	if x != nil {
		return x.UpdateUtcNano
	}
	return 0
}

func (x *UpdateCommandResult) GetPrivate() bool {
	if x != nil {
		return x.Private
	}
	return false
}

type DeleteCommand struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId int32 `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
}

func (x *DeleteCommand) Reset() {
	*x = DeleteCommand{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_internal_controller_distributed_commands_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCommand) ProtoMessage() {}

func (x *DeleteCommand) ProtoReflect() protoreflect.Message {
	mi := &file_messages_internal_controller_distributed_commands_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCommand.ProtoReflect.Descriptor instead.
func (*DeleteCommand) Descriptor() ([]byte, []int) {
	return file_messages_internal_controller_distributed_commands_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteCommand) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *DeleteCommand) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type DeleteCommandResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ok      bool   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Explain string `protobuf:"bytes,2,opt,name=explain,proto3" json:"explain,omitempty"`
}

func (x *DeleteCommandResult) Reset() {
	*x = DeleteCommandResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_internal_controller_distributed_commands_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteCommandResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCommandResult) ProtoMessage() {}

func (x *DeleteCommandResult) ProtoReflect() protoreflect.Message {
	mi := &file_messages_internal_controller_distributed_commands_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCommandResult.ProtoReflect.Descriptor instead.
func (*DeleteCommandResult) Descriptor() ([]byte, []int) {
	return file_messages_internal_controller_distributed_commands_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteCommandResult) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *DeleteCommandResult) GetExplain() string {
	if x != nil {
		return x.Explain
	}
	return ""
}

type PublishCommand struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ids           []int32 `protobuf:"varint,1,rep,packed,name=ids,proto3" json:"ids,omitempty"`
	UserId        int32   `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	UpdateUtcNano int64   `protobuf:"varint,3,opt,name=update_utc_nano,json=updateUtcNano,proto3" json:"update_utc_nano,omitempty"`
}

func (x *PublishCommand) Reset() {
	*x = PublishCommand{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_internal_controller_distributed_commands_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PublishCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishCommand) ProtoMessage() {}

func (x *PublishCommand) ProtoReflect() protoreflect.Message {
	mi := &file_messages_internal_controller_distributed_commands_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishCommand.ProtoReflect.Descriptor instead.
func (*PublishCommand) Descriptor() ([]byte, []int) {
	return file_messages_internal_controller_distributed_commands_proto_rawDescGZIP(), []int{6}
}

func (x *PublishCommand) GetIds() []int32 {
	if x != nil {
		return x.Ids
	}
	return nil
}

func (x *PublishCommand) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *PublishCommand) GetUpdateUtcNano() int64 {
	if x != nil {
		return x.UpdateUtcNano
	}
	return 0
}

type PrivateCommand struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ids           []int32 `protobuf:"varint,1,rep,packed,name=ids,proto3" json:"ids,omitempty"`
	UserId        int32   `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	UpdateUtcNano int64   `protobuf:"varint,3,opt,name=update_utc_nano,json=updateUtcNano,proto3" json:"update_utc_nano,omitempty"`
}

func (x *PrivateCommand) Reset() {
	*x = PrivateCommand{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_internal_controller_distributed_commands_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PrivateCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrivateCommand) ProtoMessage() {}

func (x *PrivateCommand) ProtoReflect() protoreflect.Message {
	mi := &file_messages_internal_controller_distributed_commands_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrivateCommand.ProtoReflect.Descriptor instead.
func (*PrivateCommand) Descriptor() ([]byte, []int) {
	return file_messages_internal_controller_distributed_commands_proto_rawDescGZIP(), []int{7}
}

func (x *PrivateCommand) GetIds() []int32 {
	if x != nil {
		return x.Ids
	}
	return nil
}

func (x *PrivateCommand) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *PrivateCommand) GetUpdateUtcNano() int64 {
	if x != nil {
		return x.UpdateUtcNano
	}
	return 0
}

type PublishCommandResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *PublishCommandResult) Reset() {
	*x = PublishCommandResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_internal_controller_distributed_commands_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PublishCommandResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishCommandResult) ProtoMessage() {}

func (x *PublishCommandResult) ProtoReflect() protoreflect.Message {
	mi := &file_messages_internal_controller_distributed_commands_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishCommandResult.ProtoReflect.Descriptor instead.
func (*PublishCommandResult) Descriptor() ([]byte, []int) {
	return file_messages_internal_controller_distributed_commands_proto_rawDescGZIP(), []int{8}
}

type PrivateCommandResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *PrivateCommandResult) Reset() {
	*x = PrivateCommandResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_internal_controller_distributed_commands_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PrivateCommandResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrivateCommandResult) ProtoMessage() {}

func (x *PrivateCommandResult) ProtoReflect() protoreflect.Message {
	mi := &file_messages_internal_controller_distributed_commands_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrivateCommandResult.ProtoReflect.Descriptor instead.
func (*PrivateCommandResult) Descriptor() ([]byte, []int) {
	return file_messages_internal_controller_distributed_commands_proto_rawDescGZIP(), []int{9}
}

var File_messages_internal_controller_distributed_commands_proto protoreflect.FileDescriptor

var file_messages_internal_controller_distributed_commands_proto_rawDesc = []byte{
	0x0a, 0x37, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72,
	0x6e, 0x61, 0x6c, 0x2f, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x6c, 0x65, 0x72, 0x2f, 0x64,
	0x69, 0x73, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x64, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x61,
	0x6e, 0x64, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x15, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x73, 0x2f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0x3f, 0x0a, 0x0d, 0x41, 0x70, 0x70, 0x65, 0x6e, 0x64, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e,
	0x64, 0x12, 0x2e, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x14, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x76, 0x31,
	0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x22, 0x25, 0x0a, 0x13, 0x41, 0x70, 0x70, 0x65, 0x6e, 0x64, 0x43, 0x6f, 0x6d, 0x6d, 0x61,
	0x6e, 0x64, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x22, 0xa7, 0x01, 0x0a, 0x0d, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73,
	0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x75, 0x73, 0x65,
	0x72, 0x49, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x66, 0x69, 0x6c, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x66, 0x69, 0x6c, 0x65, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04,
	0x74, 0x65, 0x78, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x65, 0x78, 0x74,
	0x12, 0x26, 0x0a, 0x0f, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x5f, 0x75, 0x74, 0x63, 0x5f, 0x6e,
	0x61, 0x6e, 0x6f, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0d, 0x75, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x55, 0x74, 0x63, 0x4e, 0x61, 0x6e, 0x6f, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x72, 0x69, 0x76,
	0x61, 0x74, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x70, 0x72, 0x69, 0x76, 0x61,
	0x74, 0x65, 0x22, 0x57, 0x0a, 0x13, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x43, 0x6f, 0x6d, 0x6d,
	0x61, 0x6e, 0x64, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x26, 0x0a, 0x0f, 0x75, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x5f, 0x75, 0x74, 0x63, 0x5f, 0x6e, 0x61, 0x6e, 0x6f, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x0d, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x55, 0x74, 0x63, 0x4e, 0x61, 0x6e,
	0x6f, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x07, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x22, 0x38, 0x0a, 0x0d, 0x44,
	0x65, 0x6c, 0x65, 0x74, 0x65, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x17, 0x0a, 0x07,
	0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x75,
	0x73, 0x65, 0x72, 0x49, 0x64, 0x22, 0x3f, 0x0a, 0x13, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x43,
	0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x0e, 0x0a, 0x02,
	0x6f, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x02, 0x6f, 0x6b, 0x12, 0x18, 0x0a, 0x07,
	0x65, 0x78, 0x70, 0x6c, 0x61, 0x69, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x65,
	0x78, 0x70, 0x6c, 0x61, 0x69, 0x6e, 0x22, 0x63, 0x0a, 0x0e, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x73,
	0x68, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x69, 0x64, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x05, 0x52, 0x03, 0x69, 0x64, 0x73, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73,
	0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x75, 0x73, 0x65,
	0x72, 0x49, 0x64, 0x12, 0x26, 0x0a, 0x0f, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x5f, 0x75, 0x74,
	0x63, 0x5f, 0x6e, 0x61, 0x6e, 0x6f, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0d, 0x75, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x55, 0x74, 0x63, 0x4e, 0x61, 0x6e, 0x6f, 0x22, 0x63, 0x0a, 0x0e, 0x50,
	0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x12, 0x10, 0x0a,
	0x03, 0x69, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x05, 0x52, 0x03, 0x69, 0x64, 0x73, 0x12,
	0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x26, 0x0a, 0x0f, 0x75, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x5f, 0x75, 0x74, 0x63, 0x5f, 0x6e, 0x61, 0x6e, 0x6f, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x0d, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x55, 0x74, 0x63, 0x4e, 0x61, 0x6e, 0x6f,
	0x22, 0x16, 0x0a, 0x14, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x43, 0x6f, 0x6d, 0x6d, 0x61,
	0x6e, 0x64, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x16, 0x0a, 0x14, 0x50, 0x72, 0x69, 0x76,
	0x61, 0x74, 0x65, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74,
	0x42, 0x4a, 0x5a, 0x48, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x62,
	0x64, 0x38, 0x37, 0x38, 0x2f, 0x67, 0x61, 0x6c, 0x6c, 0x65, 0x72, 0x79, 0x2f, 0x73, 0x65, 0x72,
	0x76, 0x65, 0x72, 0x2f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2f, 0x69, 0x6e, 0x74,
	0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x6c, 0x65, 0x72,
	0x2f, 0x64, 0x69, 0x73, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x64, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_messages_internal_controller_distributed_commands_proto_rawDescOnce sync.Once
	file_messages_internal_controller_distributed_commands_proto_rawDescData = file_messages_internal_controller_distributed_commands_proto_rawDesc
)

func file_messages_internal_controller_distributed_commands_proto_rawDescGZIP() []byte {
	file_messages_internal_controller_distributed_commands_proto_rawDescOnce.Do(func() {
		file_messages_internal_controller_distributed_commands_proto_rawDescData = protoimpl.X.CompressGZIP(file_messages_internal_controller_distributed_commands_proto_rawDescData)
	})
	return file_messages_internal_controller_distributed_commands_proto_rawDescData
}

var file_messages_internal_controller_distributed_commands_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_messages_internal_controller_distributed_commands_proto_goTypes = []interface{}{
	(*AppendCommand)(nil),        // 0: AppendCommand
	(*AppendCommandResult)(nil),  // 1: AppendCommandResult
	(*UpdateCommand)(nil),        // 2: UpdateCommand
	(*UpdateCommandResult)(nil),  // 3: UpdateCommandResult
	(*DeleteCommand)(nil),        // 4: DeleteCommand
	(*DeleteCommandResult)(nil),  // 5: DeleteCommandResult
	(*PublishCommand)(nil),       // 6: PublishCommand
	(*PrivateCommand)(nil),       // 7: PrivateCommand
	(*PublishCommandResult)(nil), // 8: PublishCommandResult
	(*PrivateCommandResult)(nil), // 9: PrivateCommandResult
	(*api.Message)(nil),          // 10: messages.v1.Message
}
var file_messages_internal_controller_distributed_commands_proto_depIdxs = []int32{
	10, // 0: AppendCommand.message:type_name -> messages.v1.Message
	1,  // [1:1] is the sub-list for method output_type
	1,  // [1:1] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_messages_internal_controller_distributed_commands_proto_init() }
func file_messages_internal_controller_distributed_commands_proto_init() {
	if File_messages_internal_controller_distributed_commands_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_messages_internal_controller_distributed_commands_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AppendCommand); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messages_internal_controller_distributed_commands_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AppendCommandResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messages_internal_controller_distributed_commands_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateCommand); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messages_internal_controller_distributed_commands_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateCommandResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messages_internal_controller_distributed_commands_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteCommand); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messages_internal_controller_distributed_commands_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteCommandResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messages_internal_controller_distributed_commands_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PublishCommand); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messages_internal_controller_distributed_commands_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PrivateCommand); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messages_internal_controller_distributed_commands_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PublishCommandResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messages_internal_controller_distributed_commands_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PrivateCommandResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_messages_internal_controller_distributed_commands_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_messages_internal_controller_distributed_commands_proto_goTypes,
		DependencyIndexes: file_messages_internal_controller_distributed_commands_proto_depIdxs,
		MessageInfos:      file_messages_internal_controller_distributed_commands_proto_msgTypes,
	}.Build()
	File_messages_internal_controller_distributed_commands_proto = out.File
	file_messages_internal_controller_distributed_commands_proto_rawDesc = nil
	file_messages_internal_controller_distributed_commands_proto_goTypes = nil
	file_messages_internal_controller_distributed_commands_proto_depIdxs = nil
}
