openapi: 3.0.0
info:
  title: API Specification for billing service
  description: |
    This API keeps payments and invoices
  version: 1.0.0
paths:
# INVOICE
  /billing/v2/invoices:
    post:
      summary: Create invoice via json api
      description: |
        Creates invoice and returns its id
      operationId: createInvoice

    get:
      summary: Get invoice by id
      description: |
        Get invoice by id
      operationId: getInvoice

# END INVOICE

# CANCEL PAYMENT
  /billing/v2/cancel:

# END CANCEL PAYMENT

# FULFILL PAYMENT
  /billing/v2/fulfill:

# END FULFILL PAYMENT

# PAYMENT
  /billing/v2/payments:
    post:
      summary: Start payment
      description: |
        Start payment with given invoice

    get:
      summary: Get payment
      description: |
        Get payment with given invoice

# END PAYMENT
