openapi: "3.0.0"
info:
  title: API Specification for comments
  description: |
    This API allows leaving comments for messages
  version: 1.0.0
paths:
# SEND
  /comments/v1/send:
    parameters:
      - $ref: '#/components/parameters/token'
    post:
      summary: Saves comment for a message
      description: |
        Saves comment
      operationId: sendComment
      requestBody:
        content:
          multipart/form-data:
            scheme:
              $ref: '#/components/schemas/sendComment'
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/sendCommentOk'
        "4XX":
          description: error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/serverError'

  /comments/v2/send:
    post:
      summary: Send a comment via public API
      description: |
        Send a comment via json api
      operationId: sendCommentJson
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/sendCommentJson'
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/sendCommentOk'
        "4XX":
          description: error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/serverError'
# END SEND

# UPDATE
  /comments/v1/update:
    parameters:
      - $ref: '#/components/parameters/token'
    put:
      summary: Update a comment
      description: |
        Update a comment
      operationId: updateComment
      requestBody:
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/updateComment'
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/updateCommentOk'
        "4XX":
          description: error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/serverError'

  /comments/v2/update:
    put:
      summary: Update a comment
      description: |
        Update a comment via json api
      operationId: updateCommentJson
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/comments/schemas/updateCommentJson'
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/updateCommentOk'
        "4XX":
          description: error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/serverError'

# END UPDATE

# DELETE
  /comments/v1/delete:
    parameters:
      - $ref: '#/components/parameters/token'
      - $ref: '#/components/parameters/id'
    delete:
      operationId: deleteComment
      summary: Delete comment
      description: |
        Deletes a message comment
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/deleteCommentOk'
        "4XX":
          description: error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/serverError'

  /comments/v2/delete:
    delete:
      operationId: deleteCommentJson
      summary: Delete a comment
      description: |
        Deletes a message comment
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/deleteCommentJson'
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/deleteCommentOk'
        "4XX":
          description: error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/serverError'
# END DELETE

# LIST
  /comments/v2/list:
    post:
      summary: List comments
      description: |
        List all available message comments
      operationId: listCommentsJson
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/listCommentsJson'
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                - $ref: '#/commponents/schmas/listCommentsOK'

        "4XX":
          description: error 
          content:
            application/json:
              schema:
                - $ref: '#/components/schemas/serverError'

# END LIST

# READ
  /comments/v1/read:
    parameters:
      - $ref: '#/components/parameters/token'
      - $ref: '#/components/parameters/id'
    get:
      summary: Get a comment
      description: |
        Read a comment of a message
      operationId: readComment
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                - $ref: '#/components/schemas/readCommentOk'
        "4XX":
          description: error 
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/serverError'        

  /comments/v2/read:
    post:
      summary: Get a comment
      description: |
        Read a comment via public json api
      operationId: readCommentJson
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/readCommentJson'
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                - $ref: '#/components/schemas/readCommentOk'

        "4XX":
          description: error 
          content:
            application/json:
              schema:
                - $ref: '#/components/schemas/serverError'      

# END READ

components:
  parametres:
    token:
      name: Cookie
      in: header
      schema:
        type: string
        example: token=AAAAAA

    id:
      name: id
      in: query
      required: true
      schema:
        type: integer
        example: 1

  schemas:
    serverError:
      type: object
      status:
        type: string
        default: "error"
      error:
        type: object
        properties:
          code:
            type: integer
          explain:
            type: string
          human:
            type: string

# SEND
    sendComment:
      type: object
      properties:
        message:
          type: integer
          required: true
        text:
          type: string
          required: true

    sendCommentJson:
      type: object
      properties:
        token:
          type: string
          default: ""
          required: true
        req:
          type: object
          properties:
            message:
              type: integer
              required: true
            text:
              type: string
              default: ""
              required: true

    sendCommentOk:
      type: object
      status:
        type: string
      response:
        type: object
        properties:
          description:
            type: string
          id:
            type: integer

# END SEND

# UPDATE
    updateComment:
      type: object
      properties:
        id:
          type: integer
          required: true
        text:
          type: string
          required: true

    updateCommentJson:
      type: object
      properties:
        token:
          type: string
          default: ""
          required: true
        req:
          type: object
          properties:
            id:
              type: integer
              required: true
            text:
              type: string
              default: ""
              required: true

    updateCommentOk:
      type: object
      properties:
        status:
          type: string 
          default: "ok"
        response:
          type: object
          properties:
            description:
              type: string 
              default: ""

# END UPDATE

# DELETE
    deleteCommentJson:
      type: object
      properties:
        token:
          type: string
          default: ""
          required: true
        req:
          type: object
          properties:
            id:
              type: integer
              required: true

    deleteCommentOk:
      type: object
      properties:
        status:
          type: string
          default: "ok"
        response:
          type: object
          properties:
            description:
              type: string 
              default: ""

# END DELETE

# LIST
    listCommentsJson:
      type: object
      properties:
        token:
          type: string
          default: ""
          required: true
        req:
          type: object
          properties:
            message:
              type: integer
              required: false
            user:
              type: integer
              required: false
            limit:
              type: integer
            offset:
              type: integer
            asc:
              enum: [0,1]

    listCommentsOK:
      type: object
      properties:
        status:
          type: string
          default: "ok"
        response:
          type: object
          properties:
            description:
              type: string
              default: ""
            is_last_page:
              type: boolean
            is_first_page:
              type: boolean
              required: false
            offset:
              type: integer
              required: false
            count:
              type: integer
              required: false
            total:
              type: integer
              required: false
            comments:
              type: array
              items:
                allOf:
                  - $ref: '#/components/schemas/comment'

# END LIST

# READ
    readCommentJson:
      type: object
      properties:
        token:
          type: string
          default: ""
          required: false
        req:
          type: object
          properties:
            id:
              type: integer

    readCommentOk:
      type: object
      properties:
        status:
          type: string
          default: "ok"
        response:
          type: object
          properties:
            comment:
              - $ref: '#/components/schemas/comment'

# END READ

    comment:
      type: object
      properties:
        id:
          type: integer
        user:
          type: integer
        message:
          type: integer
        text:
          type: string
        created_at:
          type: string
        updated_at:
          type: string