openapi: 3.0.0
info:
  title: API Specification for files service
  description: |
    This API handles files requests.
  version: 1.0.0
paths:
  /files/v1/upload:
    security:
      - apiKey: []
    post:
      operationId: uploadFile
      summary: Uploads a file
      description: |
        Uploads a file on server
      requestBody:
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/uploadFile'
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/uploadOk'
        "4XX":
          description: Error response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/statusErr'

  /files/v2/upload:
    parameters:
      token:
        in: path
        type: string
        required: true
    post:
      operationId: uploadFileV2
      summary: Upload a file
      description: |
        Upload a file on server with a token given in path
      requestBody:
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/uploadFile'
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/uploadOk'
        "4XX":
          description: Error response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/statusErr'              

  /files/v1/download:
    security:
      - apiKey: []
    parameters:
      user_id:
        in: path
        required: true
        type: string
      file_id:
        in: path
        required: true
        type: string
    get:
      summary: Download a file
      description: |
        Download a file for a provided user
      operationId: downloadFile

  /files/v1/status:
    get:
      operationId: getStatus
      summary: Shows server status
      responses:
        "2XX":
          description: Success response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/statusOk'
        "4XX":
          description: Error response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/statusErr'

components:
  schemas:
    uploadFile:
      type: object
      properties:
        file:
          type: string
          format: binary

    uploadOk:
      type: object
      properties:
        status:
          type: string
          default: "ok"
        description:
          type: string
          default: "saved"
        id:
          type: integer
          required: true
        name:
          type: string
          required: true

    statusOk:
      type: object
      properties:
        status:
          type: string 
          default: "ok"
        description:
          type: string 
          default: ""

    statusErr:
      type: object
      properties:
        status:
          type: string
          default: "error"
        description:
          type: string
          default: ""

  securitySchemes:
    apiKey:
      description: Cookie-based api authorization key
      type: API key
      name: api-key
      in: header