openapi: 3.0.0
info:
  title: API Specification for files service
  description: |
    This API handles files requests.
  version: 1.0.0
paths:
# LIST
  /files/v2/list:
    post:
      summary: Get user files
      description: |
        Read user files with pagination
      operationId: listFilesJson
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/componnents/schemas/listJson'
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/comopnents/schemas/listOK'
        "4XX":
          description: Error response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/serverError'
# END LIST

# PRIVATE
  /files/v2/private:
    post:
      summary: Private file
      description: |
        Private one user file
      operationId: privateFileJson
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/privateJson'
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/privateOK'
        "4XX":
          description: error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/serverError'
# END PRIVATE

# PUBLISH
  /files/v2/publish:
    post:
      summary: Publish file
      description: |
        Publish one user file
      operationId: publishFileJson
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/publishJson'
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/publishOK'
        "4XX":
          description: error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/serverError'
# END PUBLISH

# UPLOAD
  /files/v1/upload:
    security:
      - apiKey: []
    post:
      operationId: uploadFile
      summary: Uploads a file
      description: |
        Uploads a file on server
      requestBody:
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/uploadForm'
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/uploadOk'
        "4XX":
          description: Error response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/serverError'

  /files/v2/upload:
    parameters:
      token:
        in: query
        type: string
        required: true
      public:
        name: public
        in: query
        required: false
        schema:
          type: integer
          example: 1
    post:
      operationId: uploadFileV2
      summary: Upload a file
      description: |
        Upload a file on server with a token given in path
      requestBody:
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/uploadForm'
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/uploadOk'
        "4XX":
          description: Error response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/serverError'              
# END UPLOAD

# DOWNLOAD
  /files/v1/{id}/download:
    security:
      - apiKey: []
    parameters:
      id:
        in: path
        required: true
        type: integer
    get:
      summary: Download a file
      description: |
        Download a file for a provided user or public file
      operationId: downloadFile
# END DOWNLOAD

# READ
  /files/{name}:
    parameters:
      name:
        in: path
        required: true
        type: string
    get:
      summary: Read file by link
      description: |
        Read public or private file by link. Private file requires credentials
      operationID: readFile
# END READ

# STATUS
  /files/v1/status:
    get:
      operationId: getStatus
      summary: Shows server status
      responses:
        "200":
          description: ok
          content:
            text/plain:
              content:
                default: "ok"
# END STATUS

components:
  schemas:

# PUBLISH
    publishJson:
      type: object
      properties:
        token:
          type: string
          default: ""
          required: true
        req:
          type: object
          properties:
            id:
              type: integer
              required: true

    publishOk:
      type: object
      properties:
        status:
          type: string 
          default: "ok"
        response:
          type: object
          properties:
            description:
              type: string 
              default: ""
            id:
              type: integer
# END PUBLISH

# PRIVATE
    privateJson:
      type: object
      properties:
        token:
          type: string
          default: ""
          required: true
        req:
          type: object
          properties:
            id:
              type: integer
              required: true

    privateOk:
      type: object
      properties:
        status:
          type: string 
          default: "ok"
        response:
          type: object
          properties:
            description:
              type: string 
              default: ""
            id:
              type: integer
# END PRIVATE

# LIST
    listJson:
      type: object
      properties:
        token:
          type: string
          default: ""
          required: false
        req:
          type: object
          properties:
            user:
              type: integer
              required: false
            limit:
              type: integer
              required: false
            offset:
              type: integer
              required: false
            asc:
              type: integer
              required: false
              exmaple: 0

    listOK:
      type: object
      properties:
        status:
          type: string
          default: "ok"
        response:
          type: object
          properties:
            description:
              type: string
              default: ""
            is_last_page:
              type: boolean
            is_first_page:
              type: boolean
              required: false
            offset:
              type: integer
              required: false
            count:
              type: integer
              required: false
            total:
              type: integer
              required: false
            files:
              type: array
              items:
                allOf:
                  - $ref: '#/components/schemas/file'
# END LIST

# UPLOAD
    uploadForm:
      type: object
      properties:
        file:
          type: string
          format: binary

    uploadOk:
      type: object
      properties:
        status:
          type: string
          default: "ok"
        description:
          type: string
          default: "saved"
        id:
          type: integer
          required: true
        name:
          type: string
          required: true
# END UPLOAD

    file:
      type: object
      properties:
        id:
          type: integer
          example: 1
        name:
          type: string
          example: "file"
        size:
          type: integer
          example: 1024

    serverError:
      type: object
      status:
        type: string
        default: "error"
      error:
        type: object
        properties:
          code:
            type: integer
          explain:
            type: string
          human:
            type: string

  securitySchemes:
    apiKey:
      description: Cookie-based api authorization key
      type: API key
      name: api-key
      in: header