openapi: 3.0.0
info:
  title: API Specification for messages service
  description: |
    This API allows sending and reading user texts
    from messages service.
  version: 1.0.0
paths:
  /messages/v1/send:
    parameters:
      - $ref: '#/components/parameters/threadId'
    post:
      summary: Send a message
      description: |
        Send a message and replicate throughout the cluster,
        message with file possibly
      operationId: sendMessage
      requestBody:
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/sendBody'
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/sendOk'
        "4XX":
          description: error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/sendErr'

  /messages/v1/update:
    parameters:
      - $ref: '#/components/parameters/messageId'
    put:
      summary: Update a message
      description: |
        Update a message text or file. Message text cannot be empty
      operationId: updateMessage
      requestBody:
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/updateMessage'
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/updateOk'
        "4XX":
          description: error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/statusErr'

  /messages/v1/delete:
    parameters:
      - $ref: '#/components/parameters/messageId'
    delete:
      operationId: deleteMessage
      summary: Delete a message
      description: |
        Delete a message and attached file
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/statusOk'
        "4XX":
          description: error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/statusErr'

  /messages/v1/read:
    parameters:
      - $ref: '#/components/parameters/threadId'
      limit:
        in: query
        required: false
        type: integer
      offset:
        in: query
        required: false
        type: integer
      asc:
        in: query
        required: false
        schema:
          enum: [1, 0]
          type: integer
    get:
      summary: Get user messages
      description: |
        Read messages for a given user, or a specific thread
      operationId: readMessage
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    default: "ok"
                  description:
                    type: string
                    default: ""
                  is_last_page:
                    type: boolean
                  messages:
                    type: array
                    items:
                      allOf:
                        - $ref: '#/components/schemas/message'
        "4XX":
          description: error 
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    default: "fail"
                  description:
                    type: string
                    default: ""
                  messages:
                    type: array
                    items:
                      type: object
                    example: []

  /messages/v1/status:
    get:
      operationId: reportStatus
      summary: Show server status
      responses:
        "2XX":
          description: Success response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/statusOk'
        "4XX":
          description: Error response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/statusErr'

  /messages/v1/read_file:
    parameters:
      - $ref: '#/components/parameters/fileId'
    get:
      operationId: readFile
      summary: Read attached file
      description: |
        Read file attached to message
      responses:
        "2XX":
          description: |
            Success response. Returns an octet stream.
            Content-Type is a mime-type of a given file,
            or application/octet-stream
          content:
            application/octet-stream:
              schema:
                type: string
                format: binary

components:
  parameters:
    fileId:
      name: file_id
      in: query
      required: true
      schema:
        type: integer
        example: 1
    messageId:
      name: id
      in: query
      required: true
      schema:
        type: integer
        example: 1
    thread_id:
      in: query
      required: false
      type: integer

  schemas:
    updateMessage:
      type: object
      properties:
        message:
          type: string
          example: "test message"
        filename:
          type: string

    sendBody:
      example:
        text: test message
        file: ""
      type: object
      properties:
        text:
          type: string
          default: ""
        file:
          type: string
          format: binary

    sendOk:
      type: object
      properties:
        status:
          type: string
          default: ok
        description:
          type: string
          default: ""
        id:
          type: integer
          example: 1
        thread_id:
          type: integer
          example: 1
        create_utc_nano:
          type: integer
          example: 1234566700000000
        update_utc_nano:
          type: integer
          example: 1234566700000000
        file_id:
          type: integer
          example: 1234
        file_name:
          type: string
          example: "image.jpg"
        text:
          type: string
          example: "message text"
    sendErr:
      type: object
      properties:
        status:
          type: string
          default: fail
        description:
          type: string
          default: ""

    updateOk:
      type: object
      properties:
        status:
          type: string 
          default: "ok"
        description:
          type: string 
          default: ""
        id:
          type: integer
          example: 1
        update_utc_nano:
          type: integer
          example: 1234566700000000

    statusOk:
      type: object
      properties:
        status:
          type: string 
          default: "ok"
        description:
          type: string 
          default: ""

    statusErr:
      type: object
      properties:
        status:
          type: string
          default: "error"
        description:
          type: string
          default: ""

    message:
      type: object
      properties:
        id:
          type: integer
          example: 1
          readOnly: true
        user_id:
          type: integer
          example: 1
        text:
          type: string
          example: "test message"
        create_utc_nano:
          type: integer
          format: integer
        update_utc_nano:
          type: integer
          format: integer
        file:
          type: object
          properties:
            id:
              type: string
            name:
              type: string
