openapi: 3.0.0
info:
  title: API Specification for messages service
  description: |
    This API allows sending and reading user texts
    from messages service.
  version: 1.0.0
paths:
  /messages/v1/send:
    post:
      summary: Send a message
      description: |
        Send a message and replicate throughout the cluster,
        message with file possibly
      operationId: sendRequest
      requestBody:
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/sendBody'
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/sendOk'
        "4XX":
          description: error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/sendErr'

  /messages/v1/update:
    parameters:
      - $ref: '#/components/parameters/messageId'
    put:
      summary: Update a message
      description: |
        Update a message text or file. Message text cannot be empty
      operationId: updateMessage
      requestBody:
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/updateMessage'
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/statusOk'
        "4XX":
          description: error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/statusErr'

  /messages/v1/delete:
    parameters:
      - $ref: '#/components/parameters/messageId'
    delete:
      summary: Delete a message
      description: |
        Delete a message and attached file
      operationId: deleteMessage
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/statusOk'
        "4XX":
          description: error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/statusErr'

  /messages/v1/read:
    parameters:
      - $ref: '#/components/parameters/limitParam'
      - $ref: '#/components/parameters/offsetParam'
      - $ref: '#/components/parameters/ascParam'
    get:
      summary: Get user messages
      description: |
        Read messages for a given user
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    default: "ok"
                  description:
                    type: string
                    default: ""
                  islastpage:
                    type: boolean
                  messages:
                    type: array
                    items:
                      allOf:
                        - $ref: '#/components/schemas/messageObj'
        "4XX":
          description: error 
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    default: "fail"
                  description:
                    type: string
                    default: ""
                  messages:
                    type: array
                    items:
                      type: object
                    example: []
  /messages/v1/status:
    get:
      operationId: reportStatus
      summary: Show server status
      responses:
        "2XX":
          description: Success response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/statusOk'
        "4XX":
          description: Error response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/statusErr'

components:
  parameters:
    messageId:
      name: id
      in: query
      required: true
      schema:
        type: integer
        example: 1
    limitParam:
      name: limit 
      in: query
      required: false
      schema:
        type: integer
        example: 25
    offsetParam:
      name: offset
      in: query
      required: false
      schema:
        type: integer
        example: 0
    ascParam:
      name: asc
      in: query
      required: false
      schema:
        enum: [1, 0]
        type: integer

  schemas:
    updateMessage:
      type: object
      properties:
        value:
          type: string
          example: "test message"
        filename:
          type: string

    sendBody:
      example:
        message: test message
      type: object
      properties:
        message:
          type: string
          default: ""

    sendOk:
      type: object
      properties:
        status:
          type: string
          default: ok
        description:
          type: string
          default: ""
        message:
          $ref: '#/components/schemas/messageObj'
    sendErr:
      type: object
      properties:
        status:
          type: string
          default: fail
        description:
          type: string
          default: ""
    messageObj:
      type: object
      properties:
        id:
          type: integer
          example: 1
          readOnly: true
        userid:
          type: integer
          example: 1
        value:
          type: string
          example: "test message"
        createtime:
          type: string
          format: date-time
        fileid:
          type: string
        filename:
          type: string
    statusOk:
      type: object
      properties:
        status:
          type: string 
          default: "ok"
        description:
          type: string 
          default: ""
    statusErr:
      type: object
      properties:
        status:
          type: string
          default: "error"
        description:
          type: string
          default: ""
