openapi: "3.0.0"
info:
  title: API Specification for messages service
  description: |
    This API allows sending and reading user texts
    from messages service.
  version: 1.0.0
paths:
  /messages/v1/send:
    parameters:
      - $ref: '#/components/parameters/threadId'
      - $ref: '#/components/parameters/public'
    post:
      summary: Send a message
      description: |
        Send a message and replicate throughout the cluster,
        message with file possibly
      operationId: sendMessage
      requestBody:
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/sendMessage'
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/sendOk'
        "4XX":
          description: error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/sendErr'

  /messages/v2/send:
    post:
      summary: Send a message public API
      description: |
        Send a message and replicate throughout the cluster,
        message
      operationId: sendMessageJson
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/sendMessageJson'
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/sendOk'
        "4XX":
          description: error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/sendErr'

  /messages/v1/publish:
    parameters:
      - $ref: '#/components/parameters/messageId'
    put:
      summary: Make message public
      description: |
        Update private field of a message to make it public
      operationId: publicMessage
      requestBody:
        content:
          application/json:
            schema:
              type: object
              nullable: true
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/publishOk'
        "4XX":
          description: error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/statusErr'

  /messages/v1/private:
    parameters:
      - $ref: '#/components/parameters/messageId'
    put:
      summary: Make message private
      description: |
        Update private field of a message to make it private
      operationId: privateMessage
      requestBody:
        content:
          application/json:
            schema:
              type: object
              nullable: true
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/publishOk'
        "4XX":
          description: error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/statusErr'

  /messages/v1/update:
    parameters:
      - $ref: '#/components/parameters/messageId'
    put:
      summary: Update a message
      description: |
        Update a message text or file. Message text cannot be empty
      operationId: updateMessage
      requestBody:
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/updateMessage'
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/updateOk'
        "4XX":
          description: error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/statusErr'

  /messages/v1/delete:
    parameters:
      - $ref: '#/components/parameters/messageId'
      - $ref: '#/components/parameters/batchIds'
    delete:
      operationId: deleteMessage
      summary: Delete a message or messages batch
      description: |
        Deletes a user's message and attached file.
        Thread messages becomes root thread messages, i.e. thread_id = 0
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/statusOk'
        "4XX":
          description: error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/statusErr'

  /messages/v1/read:
    parameters:
      - $ref: '#/components/parameters/public'
      - $ref: '#/components/parameters/messageId'
      - $ref: '#/components/parameters/threadId'
      - $ref: '#/components/parameters/limit'
      - $ref: '#/components/parameters/offset'
      - $ref: '#/components/parameters/asc'
    get:
      summary: Get user messages or message
      description: |
        Read messages for a given user, a single message, or a specific thread,
        or public messages for a user
      operationId: readMessages
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: '#/components/schemas/messagesListResponse'
                  - $ref: '#/components/schemas/messageResponse'

        "4XX":
          description: error 
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: '#/components/schemas/messagesListFail'
                  - $ref: '#/components/schemas/messageFail'

  /messages/v1/status:
    get:
      operationId: reportStatus
      summary: Show server status
      responses:
        "2XX":
          description: Success response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/statusOk'
        "4XX":
          description: Error response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/statusErr'

  /messages/v1/read_file:
    parameters:
      - $ref: '#/components/parameters/fileId'
    get:
      operationId: readFile
      summary: Read attached file
      description: |
        Read file attached to message
      responses:
        "2XX":
          description: |
            Success response. Returns an octet stream.
            Content-Type is a mime-type of a given file,
            or application/octet-stream
          content:
            application/octet-stream:
              schema:
                type: string
                format: binary

components:
  parameters:
    fileId:
      name: file_id
      in: query
      required: true
      schema:
        type: integer
        example: 1
    messageId:
      name: id
      in: query
      required: false
      schema:
        type: integer
        example: 1
    batchIds:
      name: ids
      in: query
      required: false
      schema:
        type: array
        items:
          type: integer
    threadId:
      name: thread_id
      in: query
      required: false
      schema:
        type: integer
        example: 1
    limit:
      name: limit
      in: query
      required: false
      schema:
        type: integer
        example: 1
    offset:
      name: offset
      in: query
      required: false
      schema:
        type: integer
        example: 1
    asc:
      name: asc
      in: query
      required: false
      schema:
        enum: [1, 0]
        type: integer
    public:
      name: public
      in: query
      required: false
      schema:
        type: integer
        example: 1

  schemas:
    messagesListFail:
      type: object
      properties:
        status:
          type: string
          default: "fail"
        description:
          type: string
          default: ""
        messages:
          type: array
          items:
            type: object
          example: []

    messageFail:
      type: object
      properties:
        status:
          type: string
          default: "fail"
        description:
          type: string
          default: ""
        message:
          type: object
          default: {}

    messagesListResponse:
      type: object
      properties:
        status:
          type: string
          default: "ok"
        description:
          type: string
          default: ""
        is_last_page:
          type: boolean
        messages:
          type: array
          items:
            allOf:
              - $ref: '#/components/schemas/message'

    messageResponse:
      type: object
      properties:
        status:
          type: string
          default: "ok"
        description:
          type: string
          default: ""
        message:
          $ref: '#/components/schemas/message'

    updateMessage:
      oneOf:
        - type: object
          properties:
            public:
              type: integer
              example: 1
            text:
              type: string
              example: "test message"
            file_id:
              type: string
              example: ""
            thread_id:
              type: integer
              required: false

        - type: object
          properties:
            public:
              type: integer
              example: 1
            text:
              type: string
              example: "test message"
            file:
              type: string
              format: binary
            thread_id:
              type: integer
              required: false

    sendMessage:
      oneOf:
        - type: object
          properties:
            text:
              type: string
              default: ""
            file_id:
              type: string
              default: ""
        - type: object
          properties:
            text:
              type: string
              default: ""
            file:
              type: string
              format: binary

    sendMessageJson:
      type: object
      properties:
        text:
          type: string
          default: ""
          required: true
        file_id:
          type: string
          default: ""
          required: false
        private:
          type: boolean
          required: false
          example: 0
        thread_id:
          type: integer
          required: false

    sendOk:
      type: object
      properties:
        status:
          type: string
          default: ok
        description:
          type: string
          default: ""
        id:
          type: integer
          example: 1
        thread_id:
          type: integer
          example: 1
        create_utc_nano:
          type: integer
          example: 1234566700000000
        update_utc_nano:
          type: integer
          example: 1234566700000000
        file_id:
          type: integer
          example: 1234
        file:
          $ref: '#/components/schemas/file'
        text:
          type: string
          example: "message text"
    sendErr:
      type: object
      properties:
        status:
          type: string
          default: fail
        description:
          type: string
          default: ""

    publishOk:
      type: object
      properties:
        status:
          type: string 
          default: "ok"
        description:
          type: string 
          default: ""
        ids:
          type: array
          items:
            type: integer
        update_utc_nano:
          type: integer
          example: 1234566700000000

    updateOk:
      type: object
      properties:
        status:
          type: string 
          default: "ok"
        description:
          type: string 
          default: ""
        id:
          type: integer
          example: 1
        update_utc_nano:
          type: integer
          example: 1234566700000000

    statusOk:
      type: object
      properties:
        status:
          type: string 
          default: "ok"
        description:
          type: string 
          default: ""

    statusErr:
      type: object
      properties:
        status:
          type: string
          default: "error"
        description:
          type: string
          default: ""

    file:
      type: object
      properties:
        id:
          type: integer
          example: 1
        name:
          type: string
          example: "file"

    message:
      type: object
      properties:
        id:
          type: integer
          example: 1
          readOnly: true
        user_id:
          type: integer
          example: 1
        text:
          type: string
          example: "test message"
        create_utc_nano:
          type: integer
          format: integer
        update_utc_nano:
          type: integer
          format: integer
        private:
          type: integer
          format: integer
          example: 1
        file:
          type: object
          properties:
            id:
              type: string
            name:
              type: string
