openapi: 3.0.0
info:
  title: API Specification for telemetry service
  description: |
    This API handles telemetry requests.
  version: 1.0.0
paths:
  /telemetry/v1/send:
    post:
      summary: Send log
      description: |
        Send a log to the server
      operationId: sendLog

  /telemetry/v1/status:
    get:
      operationId: getStatus
      summary: Shows server status
      responses:
        "2XX":
          description: Success response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/statusOk'
        "4XX":
          description: Error response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/statusErr'

components:
  schemas:
    statusOk:
      type: object
      properties:
        status:
          type: string 
          default: "ok"
        description:
          type: string 
          default: ""

    statusErr:
      type: object
      properties:
        status:
          type: string
          default: "error"
        description:
          type: string
          default: ""
