openapi: 3.0.0
info:
  title: API Specification for telemetry service
  description: |
    This API handles telemetry requests.
  version: 1.0.0
paths:
# SEND
  /telemetry/v1/send:
    post:
      summary: Send log
      description: |
        Send a log to the server
      operationId: sendLog
# END SEND

# STATUS
  /telemetry/v1/status:
    get:
      operationId: getStatus
      summary: Shows server status
      responses:
        "200":
          description: ok
          content:
            text/plain:
              content:
                default: "ok"
# END STATUS

components:
  schemas:
# ERROR
    serverError:
      type: object
      status:
        type: string
        default: "error"
      error:
        type: object
        properties:
          code:
            type: integer
          explain:
            type: string
# END ERROR
