openapi: "3.0.0"
info:
  title: API Specification for threads service
  description: |
    This API allows publishing, making private
    threads, resolving paths with related messages
  version: 1.0.0
paths:
# READ
  /threads/v2/read:
    post:
      summary: Get thread
      description: |
        Reads single thread
      operationId: readThreadJson
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/readThreadJson'
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                - $ref: '#/components/schemas/readOK'
        "4XX":
          description: error
          content:
            application/json:
              schema:
                - $ref: '#/components/schemas/serverError'

# END READ

# LIST
  /threads/v2/list:
    post:
      summary: List threads
      description: |
        List and paginate threads in a given thread
      operationId: listThreadsJson
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/listThreadsJson'
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                - $ref: '#/components/schemas/listOK'
        "4XX":
          description: error
          content:
            application/json:
              schema:
                - $ref: '#/components/schemas/serverError'

# END LIST

# RESOLVE
  /threads/v2/resolve:
    post:
      summary: Resolve thread path by given id
      description: |
        It searches this thread id and returns array
        of ids, that is a path
      operationId: resolveThreadJson
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/resolveThreadJson'
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                - $ref: '#/components/schemas/resolveOK'
        "4XX":
          description: error
          content:
            application/json:
              schema:
                - $ref: '#/components/schemas/serverError'

# END RESOLVE

# REORDER
  /threads/v2/reorder:
    post:
      summary: Reorder thread to other parent or between children
      description: |
        Reorders thread between parents or between
        its siblings in a list
      operationId: reorderThreadJson
      requestBody:
        content:
          application/json:
            schema:
              - $ref: '#/components/schemas/reorderThreadJson'
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                - $ref: '#/components/schemas/reorderOK'
        "4XX":
          description: error
          content:
            application/json:
              schema:
                - $ref: '#/components/schemas/serverError'

  /threads/v1/reorder:
    parameters:
      - $ref: "#/components/parameters/token"
    post:
      summary: Reorder thread to other parent or between children
      description: |
        Reorder thread via form api
      operationId: reorderThread
      requestBody:
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/reorderThreadForm'
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                - $ref: '#/components/schemas/reorderOK'
        "4XX":
          description: error
          content:
            application/json:
              schema:
                - $ref: '#/components/schemas/serverError'

# END REORDER

# CREATE
  /threads/v2/create:
    post:
      summary: Create thread
      description: |
        Create thread ant append it in a list of threads
      operationId: createThreadJson
      requestBody:
        content:
          application/json:
            schema:
              - $ref: '#/components/schemas/createThreadJson'
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                - $ref: '#/components/schemas/createOK'
        "4XX":
          description: error
          content:
            application/json:
              schema:
                - $ref: '#/components/schemas/serverError'

# END CREATE

# DELETE
  /threads/v2/delete:
    post:
      summary: Delete thread
      description: |
        Delete thread from parent thread and move all its children
        on top list of parent thread
      operationId: deleteThreadJson
      requestBody:
        content:
          application/json:
            schema:
              - $ref: '#/components/schemas/deleteThreadJson'
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                - $ref: '#/components/schemas/deleteOK'
        "4XX":
          description: error
          content:
            application/json:
              schema:
                - $ref: '#/components/schemas/serverError'

# END DELETE

# PUBLISH
  /threads/v1/publish:
    parameters:
      - $ref: "#/components/parameters/thread"
      - $ref: "#/components/parameters/token"
    put:
      summary: Make thread public
      description: |
        Makes given thread public and all it's messages that exist.
        It does not enforce public visibility to all new messages.
        To make message public, one must make it public explicitly
      operationId: publishThread
      requestBody:
        content:
          application/json:
            schema:
              type: object
              nullable: true
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/publishOk'
        "4XX":
          description: error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/serverError'
# END PUBLISH

# PRIVATE
  /threads/v1/private:
    parameters:
      - $ref: "#/components/parameters/thread"
      - $ref: "#/components/parameters/token"
    put:
      summary: Make thread private
      description: |
        Makes given thread private and all it's messages that exist.
        To make message public in a private thread, one must make it public explicitly
      operationId: privateThread
      requestBody:
        content:
          application/json:
            schema:
              type: object
              nullable: true
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/publishOk'
        "4XX":
          description: error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/serverError'

# END PRIVATE
components:
  parameters:
    token:
      name: Cookie
      in: header
      schema:
        type: string
        example: token=AAAAAA
    thread:
      name: id
      in: query
      required: false
      schema:
        type: integer
        example: 1

  schemas:
# ERROR
    serverError:
      type: object
      status:
        type: string
        default: "error"
      error:
        type: object
        properties:
          code:
            type: integer
          explain:
            type: string
# END ERROR

# READ
    readThreadJson:
      type: object
      token:
        type: string
        example: "AAAAAA"
      request:
        type: object
        properties:
          id:
            type: integer
            required: true

    readOk:
      type: object
      status:
        type: string
      response:
        type: object
        properties:
          id:
            type: integer
          parent:
            type: integer
          prev:
            type: integer
          next:
            type: integer
          name:
            type: string
          private:
            type: boolean

# END READ

# LIST
    listThreadsJson:
      type: object
      token:
        type: string
        example: "AAAAAA"
      request:
        type: object
        properties:
          parent:
            type: integer
            required: true
          user_id:
            type: integer
            required: false
          limit:
            type: integer
            required: false
          offset:
            type: integer
            required: false

    listOK:
      type: object
      status:
        type: string
      response:
        type: object
        properties:
          ids:
            type: array
            items:
              type: integer
          count:
            type: integer
          isLastPage:
            type: boolean

# END LIST

# RESOLVE
    resolveThreadJson:
      type: object
      token:
        type: string
        example: "AAAAAA"
      request:
        type: object
        properties:
          id:
            type: integer
            required: true
          user_id: # Thread may be public
            type: integer
            required: true

    resolveOk:
      type: object
      status:
        type: string
      response:
        type: object
        properties:
          path:
            type: array
            items:
              type: integer
# END RESOLVE

# REORDER
    reorderThreadJson:
      type: object
      token:
        type: string
        example: "AAAAAA"
      request:
        type: object
        properties:
          id:
            type: integer
            required: true
          parent:
            type: integer
            required: true
          next:
            type: integer
            requried: false
          prev:
            type: integer
            required: false

    reorderThreadForm:
      type: object
      properties:
        id:
          type: integer
          default: 0
        parent:
          type: integer
          default: 0
        next:
          type: integer
          default: 0
        prev:
          type: integer
          default: 0

    reorderOK:
      type: object
      status:
        type: string
      response:
        type: object
        properties:
          description:
            type: string
          id:
            type: integer

# END REORDER

# CREATE
    createThreadJson:
      type: object
      token:
        type: string
        example: "AAAAAA"
      request:
        type: object
        properties:
          id:
            type: integer
            required: true
          parent:
            type: integer
            required: true
          next:
            type: integer
            requried: false
          prev:
            type: integer
            required: false
          name:
            type: string
            required: false
          private:
            type: string
            required: false

    createOK:
      type: object
      status:
        type: string
      response:
        type: object
        properties:
          description:
            type: string
          id:
            type: integer

# END CREATE
    deleteThreadJson:
      type: object
      token:
        type: string
        example: "AAAAAA"
      request:
        type: object
        properties:
          id:
            type: integer
            required: true

    deleteOK:
      type: object
      status:
        type: string
      response:
        type: object
        properties:
          description:
            type: string
          id:
            type: integer
# DELETE

# END DELETE 

# PUBLISH
    publishOk:
      type: object
      properties:
        status:
          type: string 
          default: "ok"
        response:
          type: object
          properties:
            description:
              type: string 
              default: ""
            id:
              type: integer
# END PUBLISH

# PRIVATE
    privateOk:
      type: object
      properties:
        status:
          type: string 
          default: "ok"
        response:
          type: object
          properties:
            description:
              type: string 
              default: ""
            id:
              type: integer
# END PRIVATE
