openapi: 3.0.0
info:
  title: API Specification for users service
  description: |
    This API allows authenticating requests.
  version: 1.0.0
paths:
  /users/v1/get:
    parameters:
      - $ref: '#/components/parameters/userId'
    get:
      summary: Get user data
      description: |
        Returns given user's metadata info
      operationId: getMe
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/user'
        "4XX":
          description: error
          content:
            application:
              schema:
                $ref: '#/components/schemas/getUserErr'

  /users/v1/auth:
    parameters:
      - in: header
        name: Cookie
        schema:
          type: string
          example: token=AAAAAA
    get:
      summary: Check if token is still valid
      description: |
        Finds user with given token,
        is token valid, returns associated user
      operationId: authUser
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/authOk'
        "401":
          description: error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/authErr'

  /users/v2/auth:
    post:
      summary: Check if token is still valid
      description: |
        Finds user with given token,
        is token valid, returns associated user
      operationId: authUserJson
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/authUserJson'
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/authOk'
        "401":
          description: error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/authErr'

  /users/v1/signup:
    post:
      summary: Registers user
      description: |
        Records user & password in database
      operationId: signupUser
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/signupUser'
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/signupOk'
        "4XX":
          description: error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/signupErr'

  /users/v2/signup:
    post:
      summary: Registers user
      description: |
        Records user & password in database
      operationId: signupUserJson
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/signupUserJson'
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/signupOkJson'
        "4XX":
          description: error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/signupErr'

  /users/v1/login:
    post:
      summary: Logs in user
      description: |
        Verifies that user is valid with given user & password
      operationId: loginUser
      requestBody:
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/loginUser'
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/loginOk'
        "4XX":
          description: error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/loginErr'

  /users/v2/login:
    post:
      summary: Logs in user via json api
      description: |
        Verifies that user is valid with given user & password
      operationId: loginUserJson
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/loginUserJson'
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/loginOk'
        "4XX":
          description: error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/loginErr'

  /users/v1/logout:
    parameters:
      - in: header
        name: Cookie
        schema:
          type: string
          example: token=AAAAAA
    post:
      summary: Logs out user
      description: |
        Logs user out, makes Cookie token expired
      operationId: logoutUser
      responses:
        "200":
          description: OK
          content:
            application/json:
              type: object
              status:
                type: string
                default: "ok"
              description:
                type: string
                default: "deleted"
        "4XX":
          description: error
          content:
            application/json:
              type: object
              status:
                type: string
                default: "error"
              description:
                type: string
                default: "failed to logout"

  /users/v2/delete:
    post:
      summary: Deletes user via json api
      description: |
        Deletes user and all releated notes, public and private
      operationId: deleteUserJson
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/deleteUserJson'
      responses:
        "200":
          description: OK
          content:
            application/json:
              type: object
              status:
                type: string
                default: "ok"
              description:
                type: string
                default: ""
        "4XX":
          description: error
          content:
            application/json:
              type: object
              status:
                type: string
                default: "error"
              description:
                type: string
                default: "failed to delete"
              expired:
                type: boolean
                default: true

  /users/v1/status:
    get:
      summary: Returns operational status
      operationId: status
      responses:
        "200":
          description: ok
          content:
            application/json:
              type: object
              status:
                type: string
                default: "ok"
              description:
                type: string
                default: "working"

components:
  parameters:
    userId:
      name: id
      in: query
      required: true
      schema:
        type: integer
        example: 1

  schemas:
    loginErr:
      type: object
      oneOf:
      - type: object
        status:
          type: string
          default: "ok"
        description:
          type: string
          default: "user not found"
      - type: object
        status:
          type: string
          default: "ok"
        description:
          type: string
          default: "no password"

    loginOk:
      type: object
      status:
        type: string
        default: ok
      description:
        type: string
        default: "authenticated"

    deleteUserJson:
      type: object
      token:
        type: string
        example: "AAAAAA"
      name:
        type: string
        example: "abc"
      password:
        type: string
        example: "pass"

    loginUserJson:
      type: object
      name:
        type: string
        example: test
      password:
        type: string
        example: "12345"

    authUserJson:
      type: object
      properties:
        token:
          type: string
          default: ""
          required: true
        req:
          type: object
          required: false

    loginUser:
      type: object
      name:
        type: string
        example: test
      password:
        type: string
        example: "12345"

    signupUserJson:
      type: object
      name:
        type: string
        example: text
      password:
        type: string
        example: "12345"

    signupUser:
      type: object
      name:
        type: string
        example: test
      password:
        type: string
        example: "12345"

    signupErr:
      oneOf:
      - type: object
        status:
          type: string
          default: "ok"
        description:
          type: string
          default: "name exists"
      - type: object
        status:
          type: string
          default: "ok"
        description:
          type: string
          default: "no name"
      - type: object
        status:
          type: string
          default: "ok"
        description:
          type: string
          default: "no password"

    getUserErr:
      type: object
      status:
        type: string
        default: "error"
      description:
        type: string
        default: ""

    signupOkJson:
      type: object
      status:
        type: string
        default: "ok"
      description:
        type: string
        default: "created"
      token:
        type: string
        example: "AAA"
      id:
        type: integer
        example: 1

    signupOk:
      type: object
      status:
        type: string
        default: "ok"
      description:
        type: string
        default: "created"

    authErr:
      type: object
      status:
        type: string
        default: "ok"
      description:
        type: string
        default: "token expired"
      expired:
        type: boolean
        default: true

    authOk:
      type: object
      status:
        type: string
        default: "ok"
      description:
        type: string
        default: "token valid"
      expired:
        type: boolean
        default: false
      user:
        $ref: '#/components/schemas/user'

    user:
      type: object
      oneOf:
      - type: object
        properties:
          id:
            type: integer
            example: 1
          name:
            type: string
            example: test
          token:
            type: string
            example: AAAAAA
          expires_utc_nano:
            type: integer
            example: 1234598000000
      - type: object
        properties:
          id:
            type: integer
            example: 1
          name:
            type: string
            example: test
