---
- name: List gallery systemd units
  hosts: gallery-stage
  become: Yes

  tasks:
  - name: List units
    community.general.systemd_info:
      unitname:
        - billing.service
        - billing-db.service
        - users.service
        - users-db.service
        - threads.service
        - threads-db.service
        - messages.service
        - messages-db.service
        - search.service
        - search-db.service
        - sessions-db.service
    register: systemd_output

  - name: Print gathered info
    ansible.builtin.debug:
      var: systemd_output.units
