---
- name: Remove stale snapshots
  hosts: hosts

  tasks:
  - name: Remove snapshots
    ansible.builtin.file:
      path: /srv/gallery/stage/data.{{ messages_port }}/raft/snapshot/snapshots/
      state: absent
