---
- name: Restart db services after data path renaming
  become: Yes
  hosts: gallery-prod

  tasks:
  - name: Restart
    ansible.builtin.service:
      name: "{{ item }}-db"
      state: restarted
      enabled: true
      daemon_reload: true
    loop:
      - sessions
      - messages
      - threads
      - search
      - billing
      - users
