---
- name: Install and setup otelcol contrib (for stage!)
  become: Yes
  hosts: infra

  tasks:
  - name: Set messages endpoints
    ansible.builtin.set_fact:
      messages_endpoints: |
        {% set server_list = [] %}
        {% for s in groups['hosts'] %}
        {%   set port = hostvars[s]['messages_http_port'] %}
        {%   set host = hostvars[s]['addr'] %}
        {%   set _ = server_list.append(host ~ ':' ~ port) %}
        {% endfor %}
        {{ server_list }}
    tags:
      - debug
      - otelcol

  - name: Setup otelcol config
    ansible.builtin.template:
      src: templates/otelcol/config.yaml.j2
      dest: /etc/otelcol-contrib/config.yaml
    tags:
      - otelcol

  - name: Restart service
    ansible.builtin.systemd_service:
      name: otelcol-contrib
      state: restarted
      enabled: true
    tags:
      - otelcol
