- name: Update endpoint services config
  hosts: hosts

  tasks:
  - name: Write endpoint json config
    ansible.builtin.template:
      src: templates/{{ item }}.json.j2
      dest: /srv/gallery/stage/{{ item }}/config/service.json
    tags:
      - json
    loop:
      - messages
      - users
      - threads
      - billing
      - search

  - name: Write
    ansible.builtin.template:
      src: templates/{{ item }}.conf.j2
      dest: /srv/gallery/stage/{{ item }}/config/service.conf
    tags:
      - conf
    loop:
      - users
      - messages
      - billing
      - search
      - threads
