---
- name: Upgrade and update package repositories on machines
  hosts: kirschen
  become: true

  tasks:
  - name: Ensure latest repositories installed
    apt: update_cache=yes

  - name: Upgrade packages
    apt:
      name: "*"
      state: latest
