---
- name: Upgrade and update package repositories on machines
  hosts: myhosts
  become: true
  vars_files:
    - /home/snd/ansible_quickstart/vaulted-vars.yaml

  tasks:
  - name: Ensure latest repositories installed
    dnf: update_cache=yes

  - name: Upgrade packages
    dnf:
      name: "*"
      state: latest
